import { IconType } from "react-icons";
import { FaLeaf } from "react-icons/fa";
import {
  GiMonsteraLeaf,
  GiVineLeaf,
  GiChestnutLeaf,
  GiYinYang,
  GiFlowerEmblem,
  GiFlowerTwirl,
  GiCottonFlower,
  GiTwirlyFlower,
  GiFlowerStar,
  GiSunCloud,
  GiLindenLeaf,
} from "react-icons/gi";
import { ImDiamonds, ImHeart, ImLeaf, ImStarFull, ImSun } from "react-icons/im";
import { IoIosFlower } from "react-icons/io";
import {
  PiAcornFill,
  PiAnchorSimpleBold,
  PiCloverFill,
  PiFlowerDuotone,
  PiFlowerLotus,
  PiFlowerLotusDuotone,
  PiFlowerLotusFill,
  PiHeartDuotone,
} from "react-icons/pi";
import {
  RiBardFill,
  RiBardLine,
  RiBlueskyFill,
  RiCentosFill,
  RiFlowerFill,
  RiLeafFill,
} from "react-icons/ri";

export const icons: IconType[] = [
  PiFlowerLotusFill,
  GiLindenLeaf,
  RiBlueskyFill,
  PiFlowerLotusDuotone,
  RiFlowerFill,
  PiCloverFill,
  GiFlowerEmblem,
  GiCottonFlower,
  ImDiamonds,
  FaLeaf,
  GiMonsteraLeaf,
  GiTwirlyFlower,
  GiYinYang,
  RiBardFill,
  RiCentosFill,
  RiLeafFill,
  PiAnchorSimpleBold,
  ImLeaf,
  ImSun,
  GiChestnutLeaf,
  PiHeartDuotone,
  PiAcornFill,
  GiFlowerTwirl,
  GiVineLeaf,
  PiFlowerDuotone,
  ImStarFull,
  PiFlowerLotus,
  GiFlowerStar,
  IoIosFlower,
  RiBardLine,
  ImHeart,
  GiSunCloud,
].filter((icon) => typeof icon === "function");
