export const dailySelfCareChecklist: string[] = [
  "Drink enough water",
  "Eat three balanced meals",
  "Take 10 minutes to stretch",
  "Practice gratitude journaling",
  "Spend 10 minutes in nature",
  "Practice mindfulness or meditation",
  "Check in with your emotions",
  "Limit social media use",
  "Engage in a hobby or passion",
  "Declutter a small area",
  "Get at least 7–9 hours of sleep",
  "Take deep, slow breaths periodically",
  "Write down three wins of the day",
  "Set a personal boundary when needed",
  "Say one kind thing to yourself",
  "Prioritize one important task",
  "Do something kind for someone else",
  "Take a mental break when needed",
  "Celebrate small achievements",
  "Forgive yourself for mistakes",
  "Read something uplifting",
  "Limit multitasking to stay present",
  "Eat a mindful snack",
  "Practice a short yoga routine",
  "Organize your space for calmness",
  "Compliment someone genuinely",
  "Visualize your goals",
  "Light a calming candle",
  "Track your mood daily",
  "Limit screen time after dinner",
  "Listen to your favorite song",
  "Repeat a favorite affirmation",
  "Reflect on one lesson learned",
  "Engage in a random act of kindness",
  "Focus on slowing down",
  "Remind yourself you are doing enough",
  "Write one thing you appreciate about yourself",
  "Spend quality time with loved ones",
  "Notice one new thing around you",
  "Smile intentionally for one minute",
];
