export const emotionalRegulationChecklist = [
  "Pause and name your emotion",
  "Use a grounding technique (5-4-3-2-1)",
  "Take 5 deep breaths",
  "Validate your feelings without judgment",
  "Write about how you feel",
  "Apply the 'STOPP' method (Stop, Take a breath, Observe, Pull back, Proceed)",
  "Distinguish emotional triggers from current reality intentionally",
  "Soothe using sensory immersion (aroma therapy, tactile grounding, ambient sounds)",
  "Engage in a creative outlet",
  "Take a mindful walk",
  "Develop a personal 'anchor statement' for emotional storms",
  "Use bilateral stimulation (walking, tapping) to regulate during overwhelm",
  "Visualize emotions as weather: temporary, natural, ever-changing",
  "Use a cooling-off period before reacting",
  "Practice self-compassion affirmations",
  "Label the intensity of your emotion (1-10)",
  "Imagine placing your emotion on a shelf",
  "Journal your emotional triggers",
  "Visualize your emotion floating away",
  "Use a stress-relief object (stress ball, fidget)",
  "Say to yourself: 'This is temporary'",
  "Use humor to shift perspective",
  "Practice emotional 'surfing' — letting emotions peak and pass without clinging",
  "Expand emotional vocabulary through regular reflection or journaling",
  "Shift focus from control to co-regulation strategies (connecting with safe others)",
  "Dance to release emotions physically",
  "Create a calming playlist",
  "Ask: 'What is this emotion trying to tell me?'",
  "Repeat a calming mantra",
  "Splash cold water on your face",
  "Use opposite action when emotions drive unhelpful behaviors",
  "Self-monitor escalation cues (body sensations, thought patterns)",
  "Use aromatherapy (lavender, eucalyptus)",
  "Color-code your emotions in a journal",
  "Distinguish between problem-solving emotions and ones needing acceptance",
  "Build emotional resilience through structured adversity simulation (in safe settings)",
  "Picture a peaceful scene",
  "Self-hug for 30 seconds",
  "Write an unsent letter",
  "Practice window of tolerance awareness: recognize hyperarousal and hypoarousal early",
  "Apply DBT skill: TIP (Temperature, Intense exercise, Paced breathing, Progressive relaxation)",
  "Redirect energy into physical movement",
  "Challenge negative interpretations",
  "Focus on breathing for 2 minutes",
  "Visualize yourself handling the emotion skillfully",
  "Use body scanning to notice tension",
  "Reframe the situation positively",
  "Create an 'emotion survival kit'",
  "Map emotions in the body using somatic visualization exercises",
  "Write out emotional 'storylines' and rewrite alternative compassionate endings",
  "Take a short nap if needed",
  "Read a favorite inspirational quote",
  "Visualize boundaries around your emotional space",
  "Plan one small self-soothing ritual",
  "Track your mood changes daily",
  "Thank your emotions for their messages",
  "Focus on what you can control",
  "Identify and validate your core emotion underneath secondary reactions",
  "Use emotion labeling with high specificity (e.g., 'I feel embarrassed' vs. 'bad')",
  "Reflect on the function of emotions: 'What is this feeling trying to protect?'",
];
