export const groundingTechniquesChecklist: string[] = [
  "Touch different textured objects intentionally (smooth, rough, soft)",
  "Hold a textured object tightly",
  "Press your feet firmly to the floor",
  "Describe your environment out loud",
  "Practice square breathing (4-4-4-4)",
  "Focus on the feeling of breathing",
  "Visualize roots growing from your feet",
  "Clutch a pillow or stuffed animal tightly",
  "Trace imaginary shapes in the air with your finger",
  "Splash cold water on your face",
  "Count backward from 100",
  "Recite a poem or quote from memory",
  "Rub your hands together vigorously and feel the warmth",
  "Walk barefoot on grass or a rug",
  "Identify the material of objects around you",
  "Close your eyes and list sounds around you",
  "Notice how clothes feel against your skin",
  "Tap your fingers lightly on a surface",
  "Hum a familiar song",
  "Clap your hands several times",
  "Walk slowly and notice each step",
  "Name 1 thing you can taste",
  "Trace the outline of your hand",
  "Say your name, age, and location aloud",
  "List all the colors you can see",
  "Name 5 things you can see",
  "Name 4 things you can feel",
  "Carry a grounding object (stone, crystal)",
  "Focus on the texture of clothing",
  "Identify patterns in your surroundings",
  "Touch something with contrasting temperatures",
  "Bounce a small ball against a wall",
  "Focus on your heartbeat",
  "Blow bubbles and watch them float",
  "Light a candle and observe it carefully",
  "Name 2 things you can smell",
  "Focus on tightening and relaxing muscles",
  "Feel the ground beneath you firmly",
  "Describe your favorite place in detail",
  "Name 3 things you can hear",
  "Place hands under cold water",
  "Pet an animal mindfully",
  "Focus on the sensations of eating",
  "Describe an object in vivid detail",
  "Stretch slowly and intentionally",
  "Draw or doodle whatever comes to mind",
  "Bounce gently on the balls of your feet",
  "Smell a strong scent (mint, citrus)",
  "Use positive grounding affirmations",
  "Draw circles repetitively",
  "Hold an ice cube and focus on the sensation",
  "Count the number of objects of a certain color",
  "Chew gum and focus on the flavor and texture",
  "Repeat your full name, location, and today's date",
  "Splash warm water on your hands and wrists",
  "Repeat grounding statements like: 'I am here, I am safe.'",
  "Press your palms together firmly and release",
  "Look for geometric patterns in your environment",
  "Focus on slow, intentional blinking",
  "Light a candle and focus on the flicker",
];
