export const healthySleepHygieneChecklist = [
  "Stick to a consistent sleep schedule",
  "Dim the lights an hour before bedtime",
  "Visualize a peaceful place",
  "Wear comfortable sleepwear",
  "Limit naps to under 30 minutes",
  "Drink a cup of herbal tea (non-caffeinated)",
  "Practice gratitude reflection before sleep",
  "Set a sleep intention",
  "Practice progressive muscle relaxation",
  "Try gentle nighttime yoga",
  "Develop a wind-down playlist",
  "Write down worries and set them aside",
  "Lower the thermostat for optimal sleep",
  "Block out disruptive noise",
  "Use a weighted blanket if comforting",
  "Keep electronics out of the bedroom",
  "Wake up at the same time daily",
  "Expose yourself to natural light in the morning",
  "Create a sleep-friendly bedroom design",
  "Create a relaxing bedtime routine",
  "Turn off screens 1 hour before bed",
  "Keep the bedroom cool and dark",
  "Use your bed only for sleep and intimacy",
  "Practice deep breathing exercises",
  "Limit heavy meals close to bedtime",
  "Stretch gently before bed",
  "Avoid alcohol before sleep",
  "Use calming scents like lavender",
  "Journal to clear your mind",
  "Listen to a sleep meditation",
  "Read a relaxing book (not digital)",
  "Avoid intense workouts close to bedtime",
  "Ensure your mattress supports comfort",
  "Try a warm bath before sleep",
  "Avoid caffeine after 2 PM",
  "Repeat a calming affirmation",
  "Focus on a soothing mental image",
  "Practice alternate nostril breathing",
  "Prioritize winding down, not multitasking",
  "Allow forgiveness for any restless nights",
];
