export const mindfulnessPracticeChecklist = [
  "Do a 5-minute body scan meditation",
  "Eat a meal mindfully",
  "Journal a stream of consciousness for 5 minutes",
  "Listen to the rise and fall of your breath",
  "Use your senses fully when outdoors",
  "Focus on the sensation of your feet touching the ground",
  "Notice the rise and fall of your chest as you breathe",
  "Take 5 deep, intentional breaths",
  "Observe your surroundings without judgment",
  "Name three things you can see",
  "Observe your thoughts without judgment for 2 minutes",
  "Walk slowly, matching your steps to your breath",
  "Do a body scan from head to toe, noticing areas of tension",
  "Notice the taste of your food",
  "Visualize your breath entering and leaving your body",
  "Accept feelings without needing to change them",
  "Pause for 1 minute of stillness",
  "Stretch slowly, paying attention to each muscle movement",
  "Write a gratitude list, focusing on the emotions behind each item",
  "Count each inhale and exhale up to 10, then start again",
  "Focus on the sensation of cool air entering your nose",
  "Light a candle and observe its flicker quietly",
  "Feel your heartbeat by placing a hand on your chest",
  "Sip a cup of tea slowly, focusing on aroma and taste",
  "Pause between activities and notice the transition",
  "Set a timer for mindful breathing — start with 3 minutes",
  "Pick a color and look around for everything that matches it",
  "Watch clouds move across the sky for a few minutes",
  "Trace an object visually without moving your head",
  "Notice the smallest sounds you can hear right now",
  "Practice mindful walking",
  "Pause before responding in conversation",
  "Practice mindful listening",
  "Reflect mindfully at the end of the day",
  "Label the feeling behind your current thoughts",
  "Pay attention to your heartbeat",
  "Visualize yourself grounded like a tree",
  "Practice mindful breathing with a mantra",
  "Smile gently and notice how it feels",
  "Move your hands slowly and intentionally",
  "Be fully present while washing dishes",
  "Notice the sensations in your body",
  "Set a mindful intention each morning",
  "Light a candle and watch the flame",
  "Connect with nature (even a houseplant)",
  "Let go of judgment when thoughts arise",
  "Practice 2 minutes of silence",
  "Notice the transition between activities",
  "Drink a cup of tea slowly",
  "Practice self-compassion mindfulness",
  "Notice how emotions shift during the day",
  "Listen deeply to ambient sounds without labeling them",
  "Feel the texture of an everyday object slowly",
  "Eat one meal today completely without distractions",
  "Trace slow circles on your palm with one finger",
  "Visualize a soft light radiating from your heart",
  "Notice and label emotions as they arise",
  "Spend 5 minutes focusing on one task",
  "Listen to calming sounds or music",
  "Practice gratitude in the moment",
  "Observe your thoughts passing by",
  "Feel the texture of an object",
  "Focus fully on brushing your teeth",
  "Practice 'noting' — label each thought as it arises (e.g., 'thinking,' 'feeling')",
  "Balance on one foot for 30 seconds while breathing deeply",
  "Spend one minute feeling the weight of your body in the chair",
  "Visualize a calm, peaceful place in vivid detail",
  "Draw without a goal, noticing only the motion of your hand",
  "Notice the temperature difference between your inhale and exhale",
  "Touch each fingertip to your thumb slowly, noticing the sensations",
];
