export const positiveThinkingChecklist = [
  "Write three positive affirmations",
  "List five things you are grateful for",
  "Celebrate a small success",
  "Challenge a negative thought",
  "Reframe a worry into a possibility",
  "Visualize your future success",
  "Say something kind to yourself",
  "Focus on one thing going right",
  "Recall a time you overcame a challenge",
  "Write a positive letter to yourself",
  "Smile for 30 seconds",
  "Find one beauty in the current moment",
  "Share positivity with someone else",
  "Watch an inspiring video",
  "Look at motivational quotes",
  "Write a 'victory list'",
  "Practice mirror affirmations",
  "Create a dream vision board",
  "Compliment a stranger",
  "Notice the strengths of others",
  "Catch yourself when being self-critical",
  "Celebrate effort, not outcomes",
  "Write your 'why' for today",
  "Surround yourself with uplifting people",
  "Engage in activities that bring joy",
  "Accept mistakes as part of growth",
  "Visualize your best self",
  "Name five positive qualities you have",
  "Laugh intentionally",
  "Watch a comedy skit",
  "Take a playful mindset toward problems",
  "See setbacks as redirections",
  "Use gratitude as a lens",
  "Repeat: 'I choose positivity.'",
  "Allow hope to exist",
  "Acknowledge your inner resilience",
  "Visualize planting seeds of positivity",
  "See yourself succeeding",
  "Focus on abundance, not lack",
  "Celebrate personal uniqueness",
];
