export const socialConnectionChecklist = [
  "Text or call a friend today",
  "Send a supportive message to someone",
  "Schedule a coffee date or meet-up",
  "Share a funny meme with someone",
  "Attend a local community event",
  "Join an online interest group",
  "Compliment someone sincerely",
  "Start a conversation with a coworker",
  "Write a handwritten note",
  "Share a personal update with someone",
  "Ask someone about their day",
  "Engage in active listening",
  "Offer to help someone with a small task",
  "Celebrate a friend's achievement",
  "Set up a regular check-in time",
  "Plan a shared activity",
  "Reach out to a distant friend",
  "Express gratitude to someone",
  "Smile at a stranger",
  "Host a game night",
  "Comment positively on social media",
  "Find a pen pal or accountability buddy",
  "Join a hobby-based club",
  "Attend a workshop or seminar",
  "Volunteer locally or online",
  "Engage in small talk intentionally",
  "Reconnect with a family member",
  "Laugh together with someone",
  "Share a positive memory with a friend",
  "Be vulnerable about something real",
  "Send someone a care package",
  "Support someone else's project",
  "Introduce yourself to a neighbor",
  "Say thank you with extra warmth",
  "Plan a group outing",
  "Host a virtual meet-up",
  "Create a shared playlist",
  "Share a book or podcast recommendation",
  "Invite someone to join you on a walk",
  "Listen without needing to fix",
];
