import { JournalPrompts } from "@/lib/interfaces&types/resources";

export const expressiveWritingPrompts: JournalPrompts[] = [
  {
    prompt:
      "What emotions am I holding onto right now, and how can I begin to release them?",
    ideas: [
      "Identify the emotions that feel most dominant in your mind and body.",
      "Describe how these emotions affect your day-to-day decisions or interactions.",
      "Recall the earliest time you remember feeling these emotions.",
      "What unmet needs are these emotions pointing to?",
      "What fears are connected to these emotions?",
      "What healthy outlets do you have—or could develop—to release them?",
      "What would it feel like to let go of one of these emotions today?",
      "Write a goodbye letter to one emotion you’re ready to release.",
      "What support would help you feel safer in releasing these emotions?",
    ],
  },
  {
    prompt: "What do I need to hear right now, and why?",
    ideas: [
      "Write a comforting letter to yourself with the words you need to hear.",
      "What are you yearning to be reassured about?",
      "Who do you wish would say these words to you—and why?",
      "What would your inner child want to hear right now?",
      "What part of your life feels the most fragile or uncertain?",
      "Imagine receiving encouragement from someone you trust—what would they say?",
      "Write a mantra you can repeat to yourself when you're struggling.",
      "How can you be your own source of emotional safety?",
      "What beliefs are you working to rebuild within yourself?",
    ],
  },
  {
    prompt: "What does emotional safety mean to me?",
    ideas: [
      "Describe a time in your life when you felt emotionally safe.",
      "What does emotional safety look like in your relationships?",
      "What makes you feel unsafe emotionally?",
      "How do you protect yourself emotionally—are those methods helpful?",
      "What people, environments, or habits make you feel secure?",
      "What boundaries do you need to create more safety?",
      "How do you show others that you’re a safe person emotionally?",
      "What changes can you make to cultivate more emotional safety in your life?",
      "How does emotional safety affect your ability to be vulnerable?",
    ],
  },
  {
    prompt: "How do I cope with emotional pain, and is it working for me?",
    ideas: [
      "List the strategies you currently use to manage pain.",
      "Which coping mechanisms feel healing, and which feel harmful?",
      "What emotional needs are you trying to meet when you turn to these habits?",
      "Describe a painful experience and how you handled it.",
      "What would a healthier coping response have looked like in that moment?",
      "What are some non-verbal ways you express or process pain?",
      "Who can you talk to when you’re in emotional distress?",
      "What would it take for you to reach out for help more often?",
      "How does your body respond when you’re avoiding emotional pain?",
    ],
  },
  {
    prompt: "What parts of myself do I still struggle to accept?",
    ideas: [
      "Make a list of traits or behaviors you judge in yourself.",
      "Where do you think those judgments came from?",
      "How do these rejected parts of you show up in your daily life?",
      "What would happen if you welcomed these parts with compassion?",
      "Write a letter from one of these ‘unacceptable’ parts to your current self.",
      "How does perfectionism affect your ability to accept yourself?",
      "What do you fear others would think if they saw this part of you?",
      "What strengths might exist in these parts you struggle with?",
      "What would self-acceptance look and feel like for you?",
    ],
  },
  {
    prompt: "What relationship in my life feels most unresolved, and why?",
    ideas: [
      "Describe the dynamics of the relationship that comes to mind.",
      "What specific event or conversation left things unsettled?",
      "What emotions do you associate with this person?",
      "What would resolution look like to you?",
      "Have you expressed how you feel to them? Why or why not?",
      "Write what you would say if nothing was holding you back.",
      "What role does forgiveness (of yourself or them) play here?",
      "How has this relationship affected your sense of self-worth?",
      "What boundaries could help you move forward, with or without them?",
    ],
  },
  {
    prompt: "What patterns keep showing up in my emotional life?",
    ideas: [
      "Identify three recurring emotional experiences or cycles.",
      "What do you notice about how you tend to respond emotionally?",
      "Where do these patterns originate from—childhood, past trauma, etc.?",
      "How do these patterns serve or protect you?",
      "In what ways do these patterns limit your emotional growth?",
      "What might it look like to interrupt one of these patterns?",
      "Write a new ending to one familiar emotional script you keep repeating.",
      "What support or tools do you need to begin changing these patterns?",
      "What emotion are you most uncomfortable sitting with—and why?",
    ],
  },
  {
    prompt:
      "What is one truth I’ve been avoiding, and what might happen if I faced it?",
    ideas: [
      "Write down the truth you’ve been avoiding, without judgment.",
      "Why is this truth hard for you to accept?",
      "What emotions come up when you think about confronting it?",
      "How is avoiding this truth impacting your emotional well-being?",
      "What freedom or clarity might come from facing it?",
      "What would you need in order to feel safe confronting this truth?",
      "How would someone you admire handle this same truth?",
      "How can this truth help you grow or evolve?",
      "What is the cost of continuing to avoid it?",
    ],
  },
  {
    prompt: "What does healing mean to me at this stage in life?",
    ideas: [
      "Define what healing currently looks like for you.",
      "How has your definition of healing changed over time?",
      "What parts of you still feel wounded or tender?",
      "How do you know when something inside you has healed?",
      "What are you doing now that supports your healing?",
      "Who or what has helped you heal in the past?",
      "What healing practices feel aligned for you right now?",
      "What areas of your life still need your attention or compassion?",
      "What would life look like if you felt truly whole?",
    ],
  },
  {
    prompt: "In what ways have I grown emotionally over the past year?",
    ideas: [
      "List some of the emotional challenges you’ve faced in the last year.",
      "How did you respond differently than you would have in the past?",
      "What emotions have you become more comfortable feeling?",
      "What have you learned about yourself through these emotional experiences?",
      "How do you now treat yourself in hard moments?",
      "What boundaries did you create that helped your emotional growth?",
      "What relationships changed as a result of your emotional progress?",
      "What are you proud of yourself for learning or unlearning?",
      "How can you celebrate or honor this emotional growth?",
    ],
  },
];
