import { JournalPrompts } from "@/lib/interfaces&types/resources";
import { FaPenAlt } from "react-icons/fa";
import { IoChatbubble } from "react-icons/io5";

export const expressiveWritingPrompts: JournalPrompts[] = [
  {
    prompt:
      "What emotions am I holding onto right now, and how can I begin to release them?",
    ideas: [
      "Identify the emotions that feel most dominant in your mind and body.",
      "Describe how these emotions affect your day-to-day decisions or interactions.",
      "Recall the earliest time you remember feeling these emotions.",
      "What unmet needs are these emotions pointing to?",
      "What fears are connected to these emotions?",
      "What healthy outlets do you have—or could develop—to release them?",
      "What would it feel like to let go of one of these emotions today?",
      "Write a goodbye letter to one emotion you’re ready to release.",
      "What support would help you feel safer in releasing these emotions?",
    ],
    Icon: IoChatbubble,
    gallery: {
      data: [
        "https://img.freepik.com/free-photo/patience-calmness-meditation-concept-peaceful-relieved-bearded-young-man-practices-yoga-exercise-keeps-hands-zen-gesture-closes-eyes-poses-pink-wall-controls-his-emotions_273609-42511.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/free-photo/pretty-joyful-dark-skinned-woman-keeps-hand-face-laughs-funny-joke-closes-eyes-from-joy-expresses-positive-emotions-wears-yellow-fashionable-jacket-poses-indoor-green-wall_273609-38300.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/premium-photo/bearded-guy-grey-sweater-grimacing_1258-6714.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/premium-photo/young-caucasian-woman-isolated-purple-wall-blink-through-fingers-embarrassed-covering-face_1187-143881.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/premium-photo/portrait-blond-girl-casual-grey-sweater-losing-control-emotions-screaming-shaking_1258-20333.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/free-photo/no-thanks-woman-feeling-dislike-rejecting-smth-disgusting-step-back-shake-hands-decline-offer-standing-beige-background_1258-301525.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/premium-photo/young-handsome-man-crosses-fingers-makes-wish_255847-1651.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/premium-photo/beautiful-asian-girl-years-stretches-her-arms-with-pleased-lazy-face-wakes-up-after-sleep-good-nap-s_1258-167258.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/free-photo/oh-thank-you-very-much-attractive-unshaven-young-male-keeps-hands-heart-expresses-gratitude-stands-against-white-wall-friendly-bearded-caucasian-guy-being-thankful-best-friend_273609-15041.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/premium-photo/laughing-young-woman-gray-sweater-scarf-with-closed-eyes-putting-hands-head-isolated-grey-wall-background-healthy-fashion-lifestyle-people-emotions-cold-season-concept-mock-up-copy-space_365776-12293.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/free-photo/people-rage-irritation-concept-emotional-outraged-crazy-woman-gestures-angrily-raises-hands-shouts-madly-husband-expresses-negative-emotions-wears-yellow-clothes-isolated-purple-wall_273609-26208.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
        "https://img.freepik.com/free-photo/negative-feelings-concept-irritated-woman-plugs-ears-clenches-teeth-complains-noise-ignores-unpleasant-conversation-wears-casual-hoodie_273609-39285.jpg?uid=R93718308&ga=GA1.1.1699338801.1739848115&semt=ais_hybrid&w=740",
      ],
    },
  },
  {
    prompt: "What do I need to hear right now, and why?",
    ideas: [
      "Write a comforting letter to yourself with the words you need to hear.",
      "What are you yearning to be reassured about?",
      "Who do you wish would say these words to you—and why?",
      "What would your inner child want to hear right now?",
      "What part of your life feels the most fragile or uncertain?",
      "Imagine receiving encouragement from someone you trust—what would they say?",
      "Write a mantra you can repeat to yourself when you're struggling.",
      "How can you be your own source of emotional safety?",
      "What beliefs are you working to rebuild within yourself?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does emotional safety mean to me?",
    ideas: [
      "Describe a time in your life when you felt emotionally safe.",
      "What does emotional safety look like in your relationships?",
      "What makes you feel unsafe emotionally?",
      "How do you protect yourself emotionally—are those methods helpful?",
      "What people, environments, or habits make you feel secure?",
      "What boundaries do you need to create more safety?",
      "How do you show others that you’re a safe person emotionally?",
      "What changes can you make to cultivate more emotional safety in your life?",
      "How does emotional safety affect your ability to be vulnerable?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "How do I cope with emotional pain, and is it working for me?",
    ideas: [
      "List the strategies you currently use to manage pain.",
      "Which coping mechanisms feel healing, and which feel harmful?",
      "What emotional needs are you trying to meet when you turn to these habits?",
      "Describe a painful experience and how you handled it.",
      "What would a healthier coping response have looked like in that moment?",
      "What are some non-verbal ways you express or process pain?",
      "Who can you talk to when you’re in emotional distress?",
      "What would it take for you to reach out for help more often?",
      "How does your body respond when you’re avoiding emotional pain?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "Write about a time you felt completely lost or confused.",
    ideas: [
      "What was the situation, and how did you feel during this time?",
      "What challenges did you face, and how did you cope with them?",
      "What did you learn about yourself during this experience?",
      "How did this experience change your perspective on confusion or uncertainty?",
      "Would you approach a similar situation differently now? Why or why not?",
    ],
    Icon: FaPenAlt,
  },
  {
    prompt: "Write about a time you felt completely out of your comfort zone.",
    ideas: [
      "What was the situation, and how did you feel going into it?",
      "What challenges did you face, and how did you cope with them?",
      "What did you learn about yourself during this experience?",
      "How did this experience change your perspective on comfort zones?",
      "Would you willingly put yourself in a similar situation again? Why or why not?",
    ],
    Icon: FaPenAlt,
    gallery: {
      data: [
        "https://plus.unsplash.com/premium_photo-1664373232551-32575df6820a?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzN8fGNvbWZvcnR8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1568527701620-6ea4ba2e2880?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDB8fGNvbWZvcnR8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1535365751156-45e3b6060cc8?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nzh8fGNvbWZvcnR8ZW58MHx8MHx8fDA%3D",
        "https://images.unsplash.com/photo-1533263470226-27d56346f62e?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8ODR8fGNvbWZvcnR8ZW58MHx8MHx8fDA%3D",
      ],
    },
  },
  {
    prompt: "Write about a time you felt truly connected to someone.",
    ideas: [
      "What was the situation, and how did you feel during this connection?",
      "What made this connection special or unique?",
      "How did this connection impact your relationship with the person?",
      "What did you learn about yourself through this connection?",
      "How can you cultivate more connections like this in your life?",
    ],
    Icon: FaPenAlt,
  },
  {
    prompt: "What parts of myself do I still struggle to accept?",
    ideas: [
      "Make a list of traits or behaviors you judge in yourself.",
      "Where do you think those judgments came from?",
      "How do these rejected parts of you show up in your daily life?",
      "What would happen if you welcomed these parts with compassion?",
      "Write a letter from one of these ‘unacceptable’ parts to your current self.",
      "How does perfectionism affect your ability to accept yourself?",
      "What do you fear others would think if they saw this part of you?",
      "What strengths might exist in these parts you struggle with?",
      "What would self-acceptance look and feel like for you?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What relationship in my life feels most unresolved, and why?",
    ideas: [
      "Describe the dynamics of the relationship that comes to mind.",
      "What specific event or conversation left things unsettled?",
      "What emotions do you associate with this person?",
      "What would resolution look like to you?",
      "Have you expressed how you feel to them? Why or why not?",
      "Write what you would say if nothing was holding you back.",
      "What role does forgiveness (of yourself or them) play here?",
      "How has this relationship affected your sense of self-worth?",
      "What boundaries could help you move forward, with or without them?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What patterns keep showing up in my emotional life?",
    ideas: [
      "Identify three recurring emotional experiences or cycles.",
      "What do you notice about how you tend to respond emotionally?",
      "Where do these patterns originate from—childhood, past trauma, etc.?",
      "How do these patterns serve or protect you?",
      "In what ways do these patterns limit your emotional growth?",
      "What might it look like to interrupt one of these patterns?",
      "Write a new ending to one familiar emotional script you keep repeating.",
      "What support or tools do you need to begin changing these patterns?",
      "What emotion are you most uncomfortable sitting with—and why?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt:
      "What is one truth I’ve been avoiding, and what might happen if I faced it?",
    ideas: [
      "Write down the truth you’ve been avoiding, without judgment.",
      "Why is this truth hard for you to accept?",
      "What emotions come up when you think about confronting it?",
      "How is avoiding this truth impacting your emotional well-being?",
      "What freedom or clarity might come from facing it?",
      "What would you need in order to feel safe confronting this truth?",
      "How would someone you admire handle this same truth?",
      "How can this truth help you grow or evolve?",
      "What is the cost of continuing to avoid it?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does healing mean to me at this stage in life?",
    ideas: [
      "Define what healing currently looks like for you.",
      "How has your definition of healing changed over time?",
      "What parts of you still feel wounded or tender?",
      "How do you know when something inside you has healed?",
      "What are you doing now that supports your healing?",
      "Who or what has helped you heal in the past?",
      "What healing practices feel aligned for you right now?",
      "What areas of your life still need your attention or compassion?",
      "What would life look like if you felt truly whole?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "In what ways have I grown emotionally over the past year?",
    ideas: [
      "List some of the emotional challenges you’ve faced in the last year.",
      "How did you respond differently than you would have in the past?",
      "What emotions have you become more comfortable feeling?",
      "What have you learned about yourself through these emotional experiences?",
      "How do you now treat yourself in hard moments?",
      "What boundaries did you create that helped your emotional growth?",
      "What relationships changed as a result of your emotional progress?",
      "What are you proud of yourself for learning or unlearning?",
      "How can you celebrate or honor this emotional growth?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does it mean to be emotionally vulnerable?",
    ideas: [
      "Describe a time you felt emotionally vulnerable.",
      "What fears or beliefs come up when you think about vulnerability?",
      "How do you define emotional vulnerability in your own words?",
      "What are the benefits of being vulnerable with others?",
      "What are the risks or challenges of being vulnerable?",
      "How can you create a safe space for vulnerability in your life?",
      "What role does trust play in your ability to be vulnerable?",
      "How can you practice vulnerability in small ways today?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does it mean to be emotionally aware?",
    ideas: [
      "Describe a time you felt emotionally aware.",
      "What qualities or traits do you associate with emotional awareness?",
      "How do you define emotional awareness in your own words?",
      "What are the benefits of being emotionally aware?",
      "What challenges or obstacles have you faced in being aware of your emotions?",
      "How can you cultivate more emotional awareness in your daily life?",
      "What role does mindfulness play in emotional awareness?",
      "How can you support others in becoming more emotionally aware?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does it mean to be emotionally intelligent?",
    ideas: [
      "Describe a time you demonstrated emotional intelligence.",
      "What qualities or traits do you associate with emotional intelligence?",
      "How do you define emotional intelligence in your own words?",
      "What are the benefits of being emotionally intelligent?",
      "What challenges or obstacles have you faced in being emotionally intelligent?",
      "How can you cultivate more emotional intelligence in your daily life?",
      "What role does empathy play in emotional intelligence?",
      "How can you support others in developing their emotional intelligence?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does it mean to be emotionally balanced?",
    ideas: [
      "Describe a time you felt emotionally balanced.",
      "What qualities or traits do you associate with emotional balance?",
      "How do you define emotional balance in your own words?",
      "What are the benefits of being emotionally balanced?",
      "What challenges or obstacles have you faced in achieving emotional balance?",
      "How can you cultivate more emotional balance in your daily life?",
      "What role does self-care play in emotional balance?",
      "How can you support others in finding their emotional balance?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does it mean to be emotionally grounded?",
    ideas: [
      "Describe a time you felt emotionally grounded.",
      "What qualities or traits do you associate with emotional grounding?",
      "How do you define emotional grounding in your own words?",
      "What are the benefits of being emotionally grounded?",
      "What challenges or obstacles have you faced in being emotionally grounded?",
      "How can you cultivate more emotional grounding in your daily life?",
      "What role does mindfulness play in emotional grounding?",
      "How can you support others in becoming more emotionally grounded?",
    ],
    Icon: IoChatbubble,
  },
  {
    prompt: "What does it mean to be emotionally connected?",
    ideas: [
      "Describe a time you felt emotionally connected to someone.",
      "What qualities or traits do you associate with emotional connection?",
      "How do you define emotional connection in your own words?",
      "What are the benefits of being emotionally connected?",
      "What challenges or obstacles have you faced in forming emotional connections?",
      "How can you cultivate more emotional connection in your daily life?",
      "What role does vulnerability play in emotional connection?",
      "How can you support others in building their emotional connections?",
    ],
    Icon: IoChatbubble,
  },
];
export const journalingPromptsexpressiveWritingPrompts = [];
