import { ServiceTierInformation } from "@/lib/interfaces&types/services";

export const serviceTierInformation: ServiceTierInformation[] = [
  {
    subServiceId: "personalized-wellness",
    tier: "basic",
    introduction:
      "Kickstart your wellness journey with foundational insights and tailored weekly plans.",
    price: 299,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 299,
  },
  {
    subServiceId: "personalized-wellness",
    tier: "growth",
    introduction:
      "Dive deeper with bi-weekly coaching to ensure sustainable change and accountability.",
    price: 499,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 2,
    totalSessions: 16,
    totalPrice: 499,
  },
  {
    subServiceId: "personalized-wellness",
    tier: "scale",
    introduction:
      "Full-scale transformation with your own coach and trainer to guide every aspect of your journey.",
    price: 899,
    durationOfSession: 75,
    sessions: 12,
    sessionsPerWeek: 2,
    totalSessions: 24,
    totalPrice: 899,
  },

  // Hormonal Balance
  {
    subServiceId: "hormonal-balance",
    tier: "basic",
    introduction:
      "Understand your hormonal health with a symptom questionnaire and general recommendations.",
    price: 199,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 199,
  },
  {
    subServiceId: "hormonal-balance",
    tier: "growth",
    introduction:
      "Get a hormone-specific lifestyle plan and functional food guide for better results.",
    price: 399,
    durationOfSession: 60,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 399,
  },
  {
    subServiceId: "hormonal-balance",
    tier: "scale",
    introduction:
      "Comprehensive support with lab test analysis, supplement protocol, and integrative coaching.",
    price: 699,
    durationOfSession: 75,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 699,
  },

  // Sleep Coaching
  {
    subServiceId: "sleep-coaching",
    tier: "basic",
    introduction:
      "Improve your sleep hygiene with a personalized assessment and core habit recommendations.",
    price: 149,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 149,
  },
  {
    subServiceId: "sleep-coaching",
    tier: "growth",
    introduction:
      "Includes sleep tracking and bi-weekly coaching to optimize your nightly routine.",
    price: 299,
    durationOfSession: 60,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 299,
  },
  {
    subServiceId: "sleep-coaching",
    tier: "scale",
    introduction:
      "Comprehensive sleep optimization with device integration and weekly sessions.",
    price: 499,
    durationOfSession: 75,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 499,
  },

  // Detox Reset
  {
    subServiceId: "detox-reset",
    tier: "basic",
    introduction:
      "Start your detox journey with a cleanse guide and meal recommendations.",
    price: 99,
    durationOfSession: 30,
    sessions: 2,
    sessionsPerWeek: 1,
    totalSessions: 2,
    totalPrice: 99,
  },
  {
    subServiceId: "detox-reset",
    tier: "growth",
    introduction:
      "Includes 1-on-1 detox coaching to guide you through the process.",
    price: 199,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 199,
  },
  {
    subServiceId: "detox-reset",
    tier: "scale",
    introduction:
      "Comprehensive detox program with meal delivery, daily check-ins, and coaching.",
    price: 399,
    durationOfSession: 60,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 399,
  },

  // Meal Planning
  {
    subServiceId: "meal-planning",
    tier: "basic",
    introduction: "Receive a one-time 7-day meal plan tailored to your needs.",
    price: 49,
    durationOfSession: 30,
    sessions: 1,
    sessionsPerWeek: 1,
    totalSessions: 1,
    totalPrice: 49,
  },
  {
    subServiceId: "meal-planning",
    tier: "growth",
    introduction:
      "Monthly meal planning with check-ins to ensure consistency and progress.",
    price: 149,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 149,
  },
  {
    subServiceId: "meal-planning",
    tier: "scale",
    introduction:
      "Live support, custom recipes, and shopping lists for a seamless experience.",
    price: 299,
    durationOfSession: 60,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 299,
  },

  // Digestive Health
  {
    subServiceId: "digestive-health",
    tier: "basic",
    introduction:
      "Get started with a digestive guide and food sensitivity overview.",
    price: 199,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 199,
  },
  {
    subServiceId: "digestive-health",
    tier: "growth",
    introduction:
      "Weekly food journal reviews and coaching to improve digestive health.",
    price: 399,
    durationOfSession: 60,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 399,
  },
  {
    subServiceId: "digestive-health",
    tier: "scale",
    introduction:
      "Comprehensive support with lab testing, GI protocol, and personalized supplements.",
    price: 699,
    durationOfSession: 75,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 699,
  },

  // Supplement Guidance
  {
    subServiceId: "supplement-guidance",
    tier: "basic",
    introduction:
      "Receive an initial consultation and personalized supplement plan.",
    price: 99,
    durationOfSession: 30,
    sessions: 1,
    sessionsPerWeek: 1,
    totalSessions: 1,
    totalPrice: 99,
  },
  {
    subServiceId: "supplement-guidance",
    tier: "growth",
    introduction:
      "Includes follow-up sessions and retesting for optimal results.",
    price: 199,
    durationOfSession: 45,
    sessions: 2,
    sessionsPerWeek: 1,
    totalSessions: 2,
    totalPrice: 199,
  },
  {
    subServiceId: "supplement-guidance",
    tier: "scale",
    introduction:
      "Comprehensive supplement regimen with discounts and ongoing support.",
    price: 399,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 399,
  },

  // Online Fitness Coaching
  {
    subServiceId: "online-fitness-coaching",
    tier: "basic",
    introduction: "Access workout templates and a monthly check-in session.",
    price: 149,
    durationOfSession: 45,
    sessions: 1,
    sessionsPerWeek: 1,
    totalSessions: 1,
    totalPrice: 149,
  },
  {
    subServiceId: "online-fitness-coaching",
    tier: "growth",
    introduction: "Includes weekly video sessions and progression tracking.",
    price: 299,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 299,
  },
  {
    subServiceId: "online-fitness-coaching",
    tier: "scale",
    introduction: "Daily accountability, custom workouts, and nutrition sync.",
    price: 599,
    durationOfSession: 75,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 599,
  },

  // Mobility Recovery
  {
    subServiceId: "mobility-recovery",
    tier: "basic",
    introduction: "Learn self-guided stretching and foam rolling protocols.",
    price: 99,
    durationOfSession: 30,
    sessions: 2,
    sessionsPerWeek: 1,
    totalSessions: 2,
    totalPrice: 99,
  },
  {
    subServiceId: "mobility-recovery",
    tier: "growth",
    introduction: "Includes video assessments and monthly mobility classes.",
    price: 199,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 199,
  },
  {
    subServiceId: "mobility-recovery",
    tier: "scale",
    introduction: "Custom recovery plan with 1-on-1 mobility coaching.",
    price: 399,
    durationOfSession: 60,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 399,
  },

  // Metabolic Optimization
  {
    subServiceId: "metabolic-optimization",
    tier: "basic",
    introduction: "Receive macro guidance and baseline metabolic habits.",
    price: 199,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 199,
  },
  {
    subServiceId: "metabolic-optimization",
    tier: "growth",
    introduction:
      "Includes wearable device sync and custom tracking dashboard.",
    price: 399,
    durationOfSession: 60,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 399,
  },
  {
    subServiceId: "metabolic-optimization",
    tier: "scale",
    introduction:
      "Advanced coaching with continuous glucose monitoring and bloodwork review.",
    price: 699,
    durationOfSession: 75,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 699,
  },

  // Group Classes
  {
    subServiceId: "group-classes",
    tier: "basic",
    introduction: "Access to weekly group fitness classes.",
    price: 49,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 49,
  },
  {
    subServiceId: "group-classes",
    tier: "growth",
    introduction: "Priority registration and access to class recordings.",
    price: 99,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 99,
  },
  {
    subServiceId: "group-classes",
    tier: "scale",
    introduction: "Unlimited access and 1-on-1 coach guidance.",
    price: 199,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 2,
    totalSessions: 8,
    totalPrice: 199,
  },

  // Guided Meditation
  {
    subServiceId: "guided-meditation",
    tier: "basic",
    introduction:
      "Access pre-recorded meditations and mindfulness app features.",
    price: 49,
    durationOfSession: 30,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 49,
  },
  {
    subServiceId: "guided-meditation",
    tier: "growth",
    introduction:
      "Join live weekly sessions and maintain a mindfulness journal.",
    price: 99,
    durationOfSession: 45,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 99,
  },
  {
    subServiceId: "guided-meditation",
    tier: "scale",
    introduction:
      "Daily meditation challenges with 1-on-1 personalized support.",
    price: 199,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 2,
    totalSessions: 8,
    totalPrice: 199,
  },

  // Neuroplasticity Coaching
  {
    subServiceId: "neuroplasticity",
    tier: "basic",
    introduction: "Daily brain training exercises and neuroplasticity tips.",
    price: 99,
    durationOfSession: 30,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 99,
  },
  {
    subServiceId: "neuroplasticity",
    tier: "growth",
    introduction: "Weekly assessments and mental performance tracking.",
    price: 199,
    durationOfSession: 45,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 199,
  },
  {
    subServiceId: "neuroplasticity",
    tier: "scale",
    introduction: "1-on-1 neurocoaching and cognitive tech stack integration.",
    price: 399,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 399,
  },

  // Therapy Sessions
  {
    subServiceId: "therapy-sessions",
    tier: "basic",
    introduction: "One 50-minute therapy session per month.",
    price: 149,
    durationOfSession: 50,
    sessions: 1,
    sessionsPerWeek: 1,
    totalSessions: 1,
    totalPrice: 149,
  },
  {
    subServiceId: "therapy-sessions",
    tier: "growth",
    introduction: "Bi-weekly therapy sessions with progress tracking.",
    price: 299,
    durationOfSession: 50,
    sessions: 2,
    sessionsPerWeek: 1,
    totalSessions: 2,
    totalPrice: 299,
  },
  {
    subServiceId: "therapy-sessions",
    tier: "scale",
    introduction:
      "Weekly therapy sessions and access to a crisis support line.",
    price: 599,
    durationOfSession: 50,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 599,
  },

  // High-Functioning Anxiety Support
  {
    subServiceId: "high-functioning-anxiety",
    tier: "basic",
    introduction: "Access an anxiety workbook and mindfulness routine.",
    price: 99,
    durationOfSession: 30,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 99,
  },
  {
    subServiceId: "high-functioning-anxiety",
    tier: "growth",
    introduction: "Weekly journaling prompts and group support sessions.",
    price: 199,
    durationOfSession: 45,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 199,
  },
  {
    subServiceId: "high-functioning-anxiety",
    tier: "scale",
    introduction: "1-on-1 coaching and nervous system regulation practices.",
    price: 399,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 399,
  },

  // ADHD Lifestyle Alignment
  {
    subServiceId: "adhd-lifestyle",
    tier: "basic",
    introduction: "Access neurodivergent-friendly productivity templates.",
    price: 99,
    durationOfSession: 30,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 99,
  },
  {
    subServiceId: "adhd-lifestyle",
    tier: "growth",
    introduction: "Bi-weekly focus coaching and routine calibration.",
    price: 199,
    durationOfSession: 45,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 199,
  },
  {
    subServiceId: "adhd-lifestyle",
    tier: "scale",
    introduction: "Personalized task system and accountability coaching.",
    price: 399,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 399,
  },

  // Trauma-Informed Regulation
  {
    subServiceId: "trauma-informed-regulation",
    tier: "basic",
    introduction:
      "Access a nervous system reset toolkit and breathing exercises.",
    price: 99,
    durationOfSession: 30,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 99,
  },
  {
    subServiceId: "trauma-informed-regulation",
    tier: "growth",
    introduction: "Weekly guided sessions and trauma-informed journaling.",
    price: 199,
    durationOfSession: 45,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 199,
  },
  {
    subServiceId: "trauma-informed-regulation",
    tier: "scale",
    introduction: "1-on-1 somatic coaching and custom regulation routine.",
    price: 399,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 399,
  },

  // Emotional Intelligence Expansion
  {
    subServiceId: "emotional-intelligence",
    tier: "basic",
    introduction: "EQ assessments and daily mood tracking.",
    price: 99,
    durationOfSession: 30,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 99,
  },
  {
    subServiceId: "emotional-intelligence",
    tier: "growth",
    introduction: "Bi-weekly EQ coaching and relationship skills development.",
    price: 199,
    durationOfSession: 45,
    sessions: 6,
    sessionsPerWeek: 1,
    totalSessions: 6,
    totalPrice: 199,
  },
  {
    subServiceId: "emotional-intelligence",
    tier: "scale",
    introduction: "Deep-dive emotional rewiring and immersive coaching.",
    price: 399,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 399,
  },
  // Team Workshops
  {
    subServiceId: "team-workshops",
    tier: "basic",
    introduction:
      "Participate in a single virtual workshop on stress management or productivity.",
    price: 299,
    durationOfSession: 60,
    sessions: 1,
    sessionsPerWeek: 1,
    totalSessions: 1,
    totalPrice: 299,
  },
  {
    subServiceId: "team-workshops",
    tier: "growth",
    introduction:
      "Access a monthly series of workshops with a wellness toolkit.",
    price: 899,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 899,
  },
  {
    subServiceId: "team-workshops",
    tier: "scale",
    introduction: "Custom curriculum and 1-on-1 coaching for team members.",
    price: 1999,
    durationOfSession: 90,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 1999,
  },

  // Burnout Prevention
  {
    subServiceId: "burnout-prevention",
    tier: "basic",
    introduction: "Company-wide burnout assessment and resources.",
    price: 499,
    durationOfSession: 60,
    sessions: 1,
    sessionsPerWeek: 1,
    totalSessions: 1,
    totalPrice: 499,
  },
  {
    subServiceId: "burnout-prevention",
    tier: "growth",
    introduction: "Monthly workshops and manager training.",
    price: 1499,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 1499,
  },
  {
    subServiceId: "burnout-prevention",
    tier: "scale",
    introduction: "Custom wellness plans for teams and HR reporting dashboard.",
    price: 2999,
    durationOfSession: 90,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 2999,
  },

  // Executive Coaching
  {
    subServiceId: "executive-coaching",
    tier: "basic",
    introduction: "Quarterly health assessments for leadership teams.",
    price: 999,
    durationOfSession: 90,
    sessions: 1,
    sessionsPerWeek: 1,
    totalSessions: 1,
    totalPrice: 999,
  },
  {
    subServiceId: "executive-coaching",
    tier: "growth",
    introduction: "Monthly coaching and goal planning sessions.",
    price: 2999,
    durationOfSession: 90,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 2999,
  },
  {
    subServiceId: "executive-coaching",
    tier: "scale",
    introduction: "Full executive wellness program with concierge support.",
    price: 5999,
    durationOfSession: 120,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 5999,
  },

  // Tech Balance
  {
    subServiceId: "tech-balance",
    tier: "basic",
    introduction: "Digital detox templates and notification control guide.",
    price: 199,
    durationOfSession: 45,
    sessions: 2,
    sessionsPerWeek: 1,
    totalSessions: 2,
    totalPrice: 199,
  },
  {
    subServiceId: "tech-balance",
    tier: "growth",
    introduction: "Device usage audit and ergonomic workstation checklist.",
    price: 399,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 399,
  },
  {
    subServiceId: "tech-balance",
    tier: "scale",
    introduction: "Custom digital wellness coaching and weekly tracking.",
    price: 799,
    durationOfSession: 60,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 799,
  },

  // Travel Recovery
  {
    subServiceId: "travel-recovery",
    tier: "basic",
    introduction: "Pre-flight and post-flight guides with hydration protocol.",
    price: 299,
    durationOfSession: 45,
    sessions: 2,
    sessionsPerWeek: 1,
    totalSessions: 2,
    totalPrice: 299,
  },
  {
    subServiceId: "travel-recovery",
    tier: "growth",
    introduction:
      "Personalized travel recovery supplements and stretch sequences.",
    price: 599,
    durationOfSession: 60,
    sessions: 4,
    sessionsPerWeek: 1,
    totalSessions: 4,
    totalPrice: 599,
  },
  {
    subServiceId: "travel-recovery",
    tier: "scale",
    introduction:
      "Global timezone syncing strategy and bio-adaptive plan with coaching.",
    price: 999,
    durationOfSession: 90,
    sessions: 8,
    sessionsPerWeek: 1,
    totalSessions: 8,
    totalPrice: 999,
  },
];
