export const adaptabilitySkillsChecklist: string[] = [
  "Reflect on a recent change and identify how you successfully adjusted.",
  "List three situations where you remained calm under uncertainty.",
  "Recall a moment when adapting your plan led to a better outcome.",
  "Practice accepting feedback without defensiveness today.",
  "Identify one belief or habit you're open to revising or letting go.",
  "Say yes to something outside your comfort zone this week.",
  "Note one skill or area of knowledge you’re currently expanding.",
  "Describe how you stayed flexible during a high-stress situation.",
  "Try solving a common task in a completely new way.",
  "Ask someone for advice and genuinely consider their perspective.",
  "Make a backup plan for a current goal and review both paths.",
  "Challenge yourself to delay judgment in an unfamiliar situation.",
  "Journal about a time when resistance to change made things harder.",
  "Try a new tool, workflow, or system—observe what works and what doesn’t.",
  "Identify a personal fear related to change and name one way to face it.",
  "Take a new route to a familiar destination and reflect on the experience.",
  "Practice mindfulness when things don’t go as planned today.",
  "Shift your schedule for one day and observe how it affects your mindset.",
  "Reframe a setback as a redirection instead of a failure.",
  "Identify an adaptive person you admire and list their key traits.",
  "Spend 10 minutes brainstorming alternatives to a current challenge.",
  "Create a list of your strengths that help you adapt.",
  "Join a discussion with people who have different perspectives.",
  "Read about someone who overcame adversity through adaptability.",
  "Practice responding instead of reacting in conversation.",
  "List all the things you cannot control—and release them.",
  "Write down three benefits of being more adaptable.",
  "Switch roles or tasks with someone for an hour to gain perspective.",
  "Say ‘I don’t know’ without shame and commit to learning.",
  "Challenge yourself to make a decision with limited information.",
  "Observe your emotional response to interruptions today.",
  "Set a small, new goal and adjust the plan halfway through.",
  "Identify one rigid area of your routine and modify it today.",
  "Try being a beginner again—start learning a new skill.",
  "Share a story with someone about how you adapted and grew.",
  "Let someone else lead and follow their process fully.",
  "Ask a ‘what if’ question to explore new solutions.",
  "Reflect on how past discomfort contributed to personal growth.",
  "Welcome constructive criticism and write down what you learned.",
  "Delay a personal judgment and replace it with curiosity.",
  "Watch a documentary or film outside your usual interests.",
  "Learn how someone in another field solves problems.",
  "Volunteer for a task that requires adaptability or improvisation.",
  "Use a failure to set a smarter, more flexible new goal.",
  "Write about how change has benefited you in the past 5 years.",
  "Accept a plan being changed by someone else today without resistance.",
  "Reimagine a goal from a different angle or timeline.",
  "Practice giving up control in a small, safe situation.",
  "Remind yourself that flexibility is a strength—not a weakness.",
  "Try meditating on the idea of impermanence.",
  "Keep a ‘change journal’ tracking your thoughts during new experiences.",
  "Revisit something you once resisted and reflect on how you feel now.",
  "Practice humility by asking someone for help on something new.",
  "Let go of the need to do something ‘the right way’ for one task.",
  "Identify what values guide your flexibility—not just preferences.",
  "Write a mantra or affirmation around openness to change.",
  "Share with a friend something new you're trying or learning.",
  "Embrace ambiguity in one conversation today.",
  "Unplug or break a pattern for one evening to see what changes.",
  "Make a pros and cons list of a current change or decision.",
  "Try a new way to express yourself creatively today.",
  "Let go of multitasking and adapt to doing one thing mindfully.",
  "Reflect on how you want to respond—not just react—next time things change.",
  "Create a ‘flexibility action plan’ with steps to stay grounded during transitions.",
  "Ask, “What can I learn here?” during moments of resistance.",
  "Use an obstacle as a cue to pivot rather than panic.",
  "Recognize that discomfort can mean growth—not danger.",
  "Observe your resistance to someone else’s idea and question it.",
  "Mentally rehearse flexibility before entering a high-stress situation.",
  "Accept that being wrong is part of adapting and growing.",
  "Reward yourself for adapting rather than controlling.",
  "Practice detaching from the outcome, and commit to the process.",
  "Let a challenge teach you something you didn’t expect.",
  "Reflect on how your adaptability has positively impacted your life.",
  "Identify a person who embodies adaptability and learn from their journey.",
  "Practice gratitude for the changes that have shaped you.",
  "Embrace the unknown as an opportunity for growth and discovery.",
  "Recognize that adaptability is a skill that can be developed over time.",
  "Celebrate your small wins in adapting to change.",
  "Reflect on how your adaptability has positively impacted your life.",
];
