export const anxietyManagementChecklist: string[] = [
  "Practice deep breathing exercises for 5 minutes to calm your mind.",
  "Identify and challenge any irrational or catastrophic thoughts.",
  "Ground yourself by naming 5 things you see, 4 you feel, 3 you hear, 2 you smell, 1 you taste",
  "Engage in physical activity for at least 20 minutes to release tension.",
  "Write down your worries to externalize them and gain perspective.",
  "Take a break from social media and news to reduce information overload.",
  "Use sensory modulation techniques (weighted blankets, textured objects)",
  "Practice progressive muscle relaxation to reduce physical tension.",
  "Practice mindfulness meditation for 10 minutes to center yourself.",
  "Drink a glass of water to stay hydrated and support body balance.",
  "Limit caffeine intake to avoid stimulating anxiety symptoms.",
  "Challenge irrational thoughts",
  "Journal your thoughts to process and release anxious feelings.",
  "Talk to a trusted friend or family member to express your emotions.",
  "Listen to calming music or nature sounds to soothe your mind.",
  "Engage in a creative activity like drawing, painting, or writing.",
  "Try a guided visualization exercise to relax your body and mind.",
  "Incorporate somatic tracking: neutrally narrate physical sensations",
  "Identify a small task you can accomplish to build a sense of control.",
  "Take a walk in nature to reset your mind and reduce stress.",
  "Anchor attention in the external environment to disrupt rumination",
  "Use positive affirmations to reframe negative or anxious thoughts.",
  "Establish a routine to bring a sense of order and predictability.",
  "Practice gratitude by writing down three things you’re thankful for.",
  "Engage in a hobby that brings you joy and distracts from anxious thoughts.",
  "Apply interoceptive exposure: intentionally focus on harmless bodily sensations of anxiety",
  "Set boundaries for yourself and others to manage overwhelming situations.",
  "Practice self-compassion and treat yourself with kindness during anxious moments.",
  "Find a quiet space and practice a short meditation session to reduce anxiety.",
  "Use essential oils like lavender or chamomile for calming effects.",
  "Take a break from work or school to engage in self-care activities.",
  "Reduce multitasking and focus on one task at a time to alleviate overwhelm.",
  "Establish a sleep routine to ensure you’re well-rested and better able to manage stress.",
  "Engage in progressive exposure hierarchies for feared situations",
  "Avoid alcohol and substances that can exacerbate anxiety symptoms.",
  "Try aromatherapy or calming scents to soothe anxiety (e.g., eucalyptus, lavender).",
  "Ask for help when you need it, whether from friends, family, or a therapist.",
  "Take a break from high-stress environments or situations.",
  "Practice mindful eating by focusing on the taste and texture of food.",
  "Use distraction techniques such as watching a movie or reading a book.",
  "Use body-oriented self-soothing like bilateral tapping (EMDR-style)",
  "Break larger tasks into smaller, more manageable steps to reduce overwhelm.",
  "Track your anxious moments and identify patterns for further understanding.",
  "Visualize a peaceful place where you feel safe and relaxed.",
  "Seek professional therapy or counseling for anxiety management support.",
  "Practice saying ‘no’ when necessary to avoid overcommitting and increasing stress.",
  "Reframe negative thoughts into more balanced, rational perspectives.",
  "Recognize that anxiety is temporary and you have the ability to cope.",
  "Engage in stretching exercises to relieve physical tension and anxiety.",
  "Avoid excessive sugar and processed foods which may impact mood.",
  "Spend time with pets to reduce stress and promote relaxation.",
  "Revisit positive past experiences to shift focus away from anxiety.",
  "Create a calm, peaceful environment at home with soft lighting and soothing décor.",
  "Practice self-care rituals such as taking a warm bath or using skincare products.",
  "Reflect on what you can control and accept what you cannot.",
  "Use a stress ball or fidget tool to release nervous energy.",
  "Focus on the present moment rather than worrying about future events.",
  "Listen to podcasts or watch videos that provide relaxation and mental health advice.",
  "Acknowledge your anxiety without judgment, allowing yourself to feel what you feel.",
  "Ask for feedback and perspective on your anxious thoughts to gain clarity.",
  "Try to avoid perfectionism, recognizing that ‘good enough’ is sufficient.",
  "Give yourself permission to take breaks without feeling guilty.",
  "Avoid procrastination by breaking tasks into smaller, actionable steps.",
  "Reflect on your strengths and how you’ve successfully managed anxiety in the past.",
  "Engage in deep, diaphragmatic breathing (4-7-8 technique).",
  "Create a list of your calming techniques and refer to them when needed.",
];