export const anxietyManagementChecklist: string[] = [
  "Practice deep breathing exercises",
  "Use grounding techniques (5-4-3-2-1)",
  "Write down your worries",
  "Practice Meta-cognitive therapy techniques: 'I am noticing I am worrying'",
  "Apply 'Name it to tame it' — verbally labeling the exact emotion",
  "Use deep diaphragmatic breathing focused on longer exhale (4 in, 7 hold, 8 out)",
  "Challenge irrational thoughts",
  "Engage in light physical exercise",
  "Journal a compassionate conversation between yourself and your anxious mind",
  "Avoid excessive caffeine",
  "Create a calm, safe space",
  "Visualize letting go of anxiety",
  "Practice square breathing: inhale 4 counts, hold 4, exhale 4, hold 4",
  "Write down your worries and set them aside in a 'worry jar'",
  "List 3 situations where you successfully overcame fear",
  "Listen to calming music",
  "Use aromatherapy or calming scents",
  "Say 'no' to overwhelming commitments",
  "Use body-oriented self-soothing like bilateral tapping (EMDR-style)",
  "Apply interoceptive exposure: intentionally focus on harmless bodily sensations of anxiety",
  "Engage in progressive exposure hierarchies for feared situations",
  "Anchor attention in the external environment to disrupt rumination",
  "Use sensory modulation techniques (weighted blankets, textured objects)",
  "Use humor to shift perspective",
  "Identify your anxiety triggers",
  "Celebrate your coping efforts",
  "Take a warm bath or shower",
  "Prioritize small, manageable tasks",
  "Recognize when anxiety peaks",
  "Set realistic expectations",
  "Remind yourself: 'This feeling will pass.'",
  "Slowly trace the outline of your hand with a finger, breathing deeply",
  "Take a mindful walk, focusing on the sound of your steps",
  "Set a small timer for 'worry time' — allow it, then move on",
  "Stick to a predictable routine",
  "Visualize a peaceful place",
  "Color or doodle creatively",
  "Use a stress ball",
  "Engage in creative expression (art, writing)",
  "Limit news consumption",
  "Name your fears without judgment",
  "Plan and organize your week",
  "Use positive self-talk",
  "Visualize yourself in a safe, calming place for 2 minutes",
  "Ground yourself by naming 5 things you see, 4 you feel, 3 you hear, 2 you smell, 1 you taste",
  "Gently tap your chest over your heart and say reassuring words",
  "Hold a comforting object and describe it in detail to yourself",
  "Create a mantra like 'I am safe. I am grounded.' and repeat it",
  "Splash cold water on your face to activate the diving reflex",
  "Journal your feelings",
  "Limit exposure to stress triggers",
  "Practice progressive muscle relaxation",
  "Reframe anxious arousal as excitement where appropriate",
  "Use distress tolerance kits: pre-made calming toolkits for high anxiety",
  "Incorporate somatic tracking: neutrally narrate physical sensations",
  "Talk to a trusted person",
  "Tense and relax each muscle group, starting from your feet upward",
  "Imagine blowing up a balloon, slowly exhaling all tension into it",
  "Create an anxiety action plan",
  "Focus on the present moment",
  "Listen to a calming podcast",
  "Drink chamomile or calming tea",
  "Practice visualization of success",
  "Sing along to a favorite song",
  "Focus on what you can control",
  "Practice gratitude in moments of stress",
  "Envision anxiety as a wave that rises and falls, not permanent",
  "Use cognitive defusion: observe anxious thoughts like leaves floating on a stream",
  "Practice 'urge surfing' when anxiety spikes, riding it out without reacting",
  "Challenge cognitive distortions: identify catastrophizing, black-and-white thinking",
  "Self-validate: 'It makes sense I feel this way given what I've experienced'",
  "Interrupt spirals with paradoxical intention: humorously exaggerate the worry briefly",
  "Practice radical acceptance when control isn't possible",
  "Visualize anxiety shrinking or moving outside your body",
  "Create a 'future-self' anchor: How would your calm future self handle this?",
];
