export const bounceBackHabitsChecklist: string[] = [
  "Acknowledge setbacks and view them as learning opportunities rather than failures.",
  "Practice gratitude daily to maintain a positive mindset, even in difficult times.",
  "Engage in regular physical activity to release stress and improve mood.",
  "Cultivate a growth mindset by reframing challenges as opportunities for personal development.",
  "Set realistic goals and break them down into manageable steps to prevent overwhelm.",
  "Focus on the present moment through mindfulness or meditation to reduce anxiety and improve clarity.",
  "Seek support from friends, family, or a mentor when you’re feeling discouraged.",
  "Reflect on past challenges and the strategies that helped you overcome them.",
  "Develop a strong routine to provide structure and a sense of control in times of uncertainty.",
  "Celebrate small wins and progress to boost your confidence and motivation.",
  "Prioritize self-care activities that nurture your physical, emotional, and mental well-being.",
  "Take time for hobbies and activities that bring you joy and relaxation.",
  "Commit to daily affirmations to reinforce positive self-talk and build resilience.",
  "Limit exposure to negative news or toxic environments that contribute to stress.",
  "Practice deep breathing or relaxation techniques to calm your mind during stressful moments.",
  "Take regular breaks to avoid burnout and maintain mental clarity throughout the day.",
  "Establish boundaries to protect your time and energy from unnecessary stress.",
  "Surround yourself with supportive, positive people who encourage your growth.",
  "Learn from mistakes and use them as stepping stones toward future success.",
  "Focus on your strengths and leverage them to overcome obstacles.",
  "Maintain a sense of humor and find lightness in tough situations to reduce stress.",
  "Visualize success and use positive imagery to reinforce your resilience.",
  "Create a list of motivating affirmations or quotes to refer to when you need encouragement.",
  "Reevaluate your goals regularly to ensure they align with your values and adjust as needed.",
  "Commit to practicing patience with yourself as you navigate challenges.",
  "Practice self-compassion and avoid self-criticism when things don’t go as planned.",
  "Stay organized with tools like planners or digital apps to track progress and reduce stress.",
  "Learn to accept what’s beyond your control and focus on what you can change.",
  "Connect with nature regularly to reset and improve your emotional balance.",
  "Engage in creative expression, such as journaling or art, to process emotions and boost resilience.",
  "Stay curious and open-minded, viewing challenges as puzzles to solve rather than insurmountable problems.",
  "Develop an “it’s okay to not be okay” attitude to normalize setbacks and stress.",
  "Recognize your limits and take proactive steps to avoid overcommitting yourself.",
  "Make time for relaxation techniques like progressive muscle relaxation or aromatherapy.",
  "Develop a support network of like-minded individuals to share experiences and offer mutual support.",
  "Focus on building one habit at a time to avoid feeling overwhelmed by too many changes.",
  "Celebrate your resilience, recognizing the strength you’ve shown in overcoming adversity.",
  "Identify areas where you can improve, and set small, achievable goals to make progress.",
  "Create a positive evening routine to wind down and prepare for the next day.",
  "Let go of the need for perfection and embrace progress over perfection.",
  "Shift your perspective by looking for the silver lining in difficult situations.",
  "Practice forgiveness toward yourself and others to release emotional burdens.",
  "Limit negative self-talk and replace it with empowering thoughts and statements.",
  "Seek out educational resources or workshops to build new skills and enhance your adaptability.",
  "Keep a journal to track your progress, setbacks, and personal insights.",
  "Identify and acknowledge your emotional triggers, and develop strategies to cope with them.",
  "Develop an optimistic outlook on life, focusing on what’s going well rather than what’s going wrong.",
  "Make time for social connections and enjoy meaningful conversations with friends or family.",
  "Take care of your physical health by maintaining a balanced diet, staying hydrated, and getting enough sleep.",
  "Commit to lifelong learning and self-improvement to continue growing through challenges.",
  "Allow yourself to take breaks when needed, and resist the urge to push through when fatigued.",
  "Be mindful of your internal dialogue, and practice self-encouragement during tough times.",
  "Incorporate relaxation exercises into your day to help lower stress and improve resilience.",
  "Evaluate your progress regularly and adjust your strategies to ensure continuous improvement.",
  "Accept setbacks as a natural part of life and trust in your ability to recover and grow stronger.",
  "Practice gratitude by reflecting on the positive aspects of your life, even during difficult times.",
  "Engage in community service or volunteer work to foster a sense of purpose and connection.",
  "Reflect on your values and ensure your actions align with them to maintain a sense of purpose.",
  "Practice active listening in conversations to foster deeper connections and understanding.",
  "Engage in regular check-ins with yourself to assess your mental and emotional well-being.",
  "Create a vision board or list of goals to remind yourself of what you want to achieve and stay motivated.",
  "Limit your exposure to negative people or environments that drain your energy and contribute to burnout.",
  "Seek out positive affirmations or motivational quotes to inspire and uplift you throughout the day.",
  "Consider working with a coach or mentor to help you navigate challenges and stay focused on your goals.",
  "Practice active listening in conversations to foster deeper connections and understanding with others.",
  "Engage in regular check-ins with yourself to assess your mental and emotional well-being.",
  "Create a vision board or list of goals to remind yourself of what you want to achieve and stay motivated.",
  "Limit your exposure to negative people or environments that drain your energy and contribute to burnout.",
  "Seek out positive affirmations or motivational quotes to inspire and uplift you throughout the day.",
  "Consider working with a coach or mentor to help you navigate challenges and stay focused on your goals.",
  "Practice active listening in conversations to foster deeper connections and understanding with others.",
  "Engage in regular check-ins with yourself to assess your mental and emotional well-being.",
];
