export const burnoutPreventionChecklist: string[] = [
  "Identify and set clear boundaries between work and personal life to avoid overcommitment.",
  "Take regular breaks throughout the day to recharge and prevent mental fatigue.",
  "Prioritize sleep and ensure you get sufficient rest every night.",
  "Engage in physical activity or exercise to boost energy levels and reduce stress.",
  "Practice mindfulness or meditation daily to clear your mind and stay grounded.",
  "Schedule downtime or ‘me-time’ regularly to relax and enjoy activities that recharge you.",
  "Set realistic expectations and avoid overloading yourself with unrealistic deadlines or tasks.",
  "Learn to say ‘no’ when you’re at capacity and protect your time from unnecessary stressors.",
  "Make time for socializing with friends or family to nurture your relationships and provide emotional support.",
  "Delegate tasks at work or in your personal life to share the load and reduce overwhelm.",
  "Engage in creative hobbies or passions to bring joy and fulfillment into your routine.",
  "Take short walks or stretch regularly throughout the day to combat the physical effects of sitting or working long hours.",
  "Monitor your stress levels and check in with yourself regularly to ensure you're not becoming overwhelmed.",
  "Avoid multitasking—focus on one task at a time to reduce mental fatigue and increase productivity.",
  "Plan your day and week in advance to prioritize your most important tasks and avoid last-minute stress.",
  "Ensure you're taking vacations or short breaks from work to step away and disconnect.",
  "Maintain a healthy diet to fuel your body with the necessary nutrients to stay energized and focused.",
  "Practice deep breathing exercises to relieve stress and improve mental clarity during the day.",
  "Limit your caffeine intake to avoid dependency and sleep disruptions.",
  "Evaluate your work-life balance and make adjustments where needed to prevent burnout from creeping in.",
  "Reflect on what brings you fulfillment and joy, and incorporate more of those activities into your routine.",
  "Keep a gratitude journal to focus on the positive aspects of your life and reduce negative thinking patterns.",
  "Seek professional help, such as therapy or counseling, if you feel you’re struggling with burnout or stress.",
  "Engage in regular self-care practices such as taking a bath, enjoying a favorite hobby, or reading.",
  "Foster a growth mindset by recognizing your accomplishments and celebrating small wins.",
  "Consider adjusting your work environment (e.g., workspace organization, lighting, etc.) to improve comfort and focus.",
  "Stay connected with your support system, including friends, family, or coworkers who can offer encouragement.",
  "Try to maintain a sense of purpose in your work by setting personal goals and finding meaning in what you do.",
  "Take regular vacations or weekend getaways to disconnect from your responsibilities and reset.",
  "Acknowledge when you're feeling overwhelmed and take immediate steps to reduce stress before it builds up.",
  "Avoid toxic work environments or individuals that contribute to stress and burnout.",
  "Break up large projects into smaller, more manageable tasks to reduce feelings of overwhelm.",
  "Use positive self-talk to combat negative thoughts and affirm your ability to handle challenges.",
  "Stay organized with a planner or digital tool to keep track of deadlines and responsibilities.",
  "Be kind to yourself—recognize that it's okay to have off days and not be at your best all the time.",
  "Seek regular feedback from colleagues or supervisors to ensure you’re on track and feel supported.",
  "Recognize when you need to take time off and allow yourself to rest without guilt.",
  "Reduce exposure to negative news or social media content that may contribute to stress.",
  "Establish a calming pre-sleep routine to improve sleep quality and reduce nighttime anxiety.",
  "Reassess your goals regularly to ensure they align with your values and bring you satisfaction.",
  "Limit unnecessary meetings or work obligations that drain your energy or contribute to feelings of burnout.",
  "Find ways to make your workspace enjoyable and comfortable to increase your well-being at work.",
  "Stay connected with nature—spend time outdoors or around plants to improve mood and reduce stress.",
  "Stay hydrated throughout the day to maintain focus and energy levels.",
  "Avoid perfectionism and accept that not everything has to be done perfectly to be good enough.",
  "Set aside time for deep relaxation—engage in activities like yoga, meditation, or listening to soothing music.",
  "Ensure that you're celebrating your successes, both big and small, to maintain motivation and reduce burnout.",
  "Take a step back when you're feeling frustrated, and re-evaluate the situation to find a more balanced approach.",
  "Practice self-compassion—be gentle with yourself and recognize that taking breaks is part of being productive.",
  "Cultivate a sense of humor—try to find light moments throughout the day to laugh and reduce tension.",
  "Recognize your emotional triggers and create strategies for managing them before they escalate.",
  "Join a community or support group for like-minded individuals who understand your challenges and can offer advice.",
  "Avoid isolating yourself—reach out to others when you're feeling disconnected or overwhelmed.",
  "Accept that you can't do everything and allow yourself to rest and recharge when needed.",
  "Review your achievements regularly and give yourself credit for the progress you've made.",
  "Identify activities that you enjoy and that make you feel relaxed, and make time for them regularly.",
  "Monitor your energy levels and adjust your schedule to accommodate periods of rest and productivity.",
  "Use relaxation techniques, such as progressive muscle relaxation or aromatherapy, to unwind after a busy day.",
  "Establish a work rhythm that aligns with your personal preferences and helps you maintain focus and productivity.",
  "Stay flexible with your plans—sometimes it's necessary to pivot or adjust your goals to reduce stress.",
  "Practice gratitude by acknowledging the positive aspects of your life and the support you receive from others.",
  "Engage in regular check-ins with yourself to assess your mental and emotional well-being.",
  "Create a vision board or list of goals to remind yourself of what you want to achieve and stay motivated.",
  "Limit your exposure to negative people or environments that drain your energy and contribute to burnout.",
  "Seek out positive affirmations or motivational quotes to inspire and uplift you throughout the day.",
  "Consider working with a coach or mentor to help you navigate challenges and stay focused on your goals.",
  "Practice active listening in conversations to foster deeper connections and understanding with others.",
  "Engage in regular self-reflection to identify areas of your life that may need adjustment or improvement.",
  "Create a list of coping strategies that work for you and keep them handy for when you need them.",
];
