export const burnoutPreventionChecklist: string[] = [
  "Take regular screen breaks",
  "Set clear work boundaries",
  "Prioritize self-care activities",
  "Use positive affirmations specific to work stress",
  "Identify and cut energy leaks",
  "Commit to learning a new skill just for fun",
  "Break larger projects into manageable parts",
  "Visualize yourself thriving",
  "Limit multitasking",
  "Reflect weekly on achievements",
  "Practice self-compassion affirmations",
  "Visualize completing tasks with ease",
  "Limit excessive exposure to negative news",
  "Practice saying 'no' without guilt",
  "Use a task management system",
  "Limit overtime whenever possible",
  "Celebrate completed tasks",
  "Engage in non-work hobbies",
  "Schedule mental health days",
  "Reflect on work-life balance weekly",
  "Use a visual task board to stay organized",
  "Express gratitude daily",
  "Delegate tasks when possible",
  "Create a calming workspace",
  "Drink water throughout the day",
  "Pause to stretch every hour",
  "Rotate challenging tasks with easier ones",
  "Block off 'do not disturb' focus hours",
  "Practice a hobby unrelated to work",
  "Review and adjust workload expectations",
  "End your workday with a shutdown ritual",
  "Stay aware of resentment signs",
  "Give yourself permission to pause",
  "Create a 'joy list' to spark daily happiness",
  "Reflect on your core passions monthly",
  "Incorporate micro-breaks during long meetings",
  "Take a digital detox weekend",
  "Laugh regularly to de-stress",
  "Use mindfulness techniques between tasks",
  "Take full lunch breaks away from your desk",
  "Focus on progress, not perfection",
  "Use breathing techniques during stress spikes",
  "Ask for help when needed",
  "Celebrate progress weekly, even small wins",
  "Set a timer for deep work vs. break cycles",
  "Prioritize sleep consistently",
  "Set daily realistic goals",
  "Allow imperfection in your work",
  "Recognize signs of overwhelm",
  "Schedule 'unplugged' time daily",
  "Talk openly about stress",
  "Identify your energy drains",
  "Seek mentorship or peer support",
  "Identify your core work values",
  "Balance productivity with creativity",
  "Create clear start/end work rituals",
  "Focus on the 'why' behind your work",
  "Practice 'leaving work at work' rituals",
  "Develop a soothing work environment (plants, light)",
  "Shift perfectionism to healthy striving",
];
