export const crisisCopingPlanChecklist: string[] = [
  "Take slow, deep breaths to ground yourself and reduce immediate anxiety.",
  "Pause and remind yourself that this is a temporary crisis, and it will pass.",
  "Reach out to a trusted friend, family member, or counselor for emotional support.",
  "Create a safe space by finding a quiet area or sitting in a comfortable position.",
  "Use a grounding technique, such as the 5-4-3-2-1 exercise (identify 5 things you can see, 4 you can touch, 3 you can hear, 2 you can smell, 1 you can taste).",
  "Practice self-soothing with calming music, aromatherapy, or a weighted blanket.",
  "Reaffirm your coping strengths and remind yourself of past moments where you've handled difficult situations.",
  "Break down the situation into smaller, manageable parts and focus on one thing at a time.",
  "Use positive self-talk to counter negative thoughts. For example, “I can handle this,” or “This feeling is temporary.”",
  "Write down your thoughts and feelings in a journal to release emotional tension.",
  "Distract yourself with a hobby or activity that requires focus (e.g., coloring, knitting, puzzles).",
  "Reach for a relaxation tool, like progressive muscle relaxation or visualization, to calm your body.",
  "If feeling overwhelmed, focus on the present moment and avoid catastrophic thinking about the future.",
  "Use a crisis hotline or text line to talk with someone who can provide immediate support.",
  "Drink a glass of water to hydrate and help clear your mind.",
  "Engage in a calming ritual, such as sipping herbal tea or taking a warm bath.",
  "Remember your coping strategies and keep a list handy for easy access during moments of crisis.",
  "Try to identify the underlying trigger of the crisis and assess whether it's something that can be addressed right away.",
  "If you're feeling dissociated or detached, engage in an activity that brings you back to your body (e.g., physical activity, drinking water, or a warm shower).",
  "Take a break from social media or any digital content that might be exacerbating your emotional state.",
  "Call a mental health professional or therapist for immediate consultation or guidance.",
  "If feeling physically unsafe, create a plan to leave any dangerous situation immediately and find a secure location.",
  "Reassure yourself that it's okay to feel overwhelmed, and you don't need to have everything figured out right now.",
  "Practice mindfulness by focusing on the sensations of your breath or the environment around you.",
  "Use guided meditation or mindfulness apps to help center your thoughts and calm your mind.",
  "List any immediate actions that can help alleviate the emotional pressure (e.g., walking, calling a friend, taking a break).",
  "Take a moment to identify any positive affirmations or mantras you can repeat to yourself during the crisis.",
  "Remember your support network and the people who care about you—reaching out can be grounding.",
  "Write down a short-term plan of action to help you manage the situation step by step.",
  "Reflect on how you’ve handled past crises and remind yourself that you have the strength to manage this one.",
  "Reassess your environment—if it's too chaotic, try to reduce distractions or remove yourself from overstimulating situations.",
  "If you’re able to, take a short walk outside to get fresh air and change your environment.",
  "Use a stress ball, fidget tool, or any tactile object to ground yourself physically.",
  "Turn off negative stimuli in your environment (e.g., turn off the news or any distressing media).",
  "Try to change your perspective on the crisis by reframing it—ask yourself what you can learn from the situation.",
  "If the emotional intensity continues, give yourself permission to take a break from any responsibilities.",
  "Ask for help with immediate practical tasks if you feel overwhelmed by daily responsibilities.",
  "Write a list of things you can control in the moment and focus your energy on them.",
  "Ask yourself, 'What do I need right now?' and address your emotional needs step by step.",
  "Recognize that feeling emotional pain is a normal part of life, and seeking help or using coping strategies is a sign of strength.",
  "Try to practice self-compassion and remind yourself that it's okay not to be okay sometimes.",
  "When possible, take a mental health day to rest and recharge before returning to regular responsibilities.",
  "If you’ve used any tools or techniques that helped, make a note of them for future reference.",
  "Allow yourself time to recover, knowing that healing can take time and it’s okay to pace yourself.",
  "If this is a recurring situation, consider making a long-term plan with a therapist to manage future crises.",
  "Focus on small victories—if you were able to complete a basic task or calm yourself down, celebrate that progress.",
  "Reaffirm that this situation will pass and you can move forward from it with resilience.",
];
