export const depressionSupportChecklist: string[] = [
  "Start your day by practicing gratitude and noting three things you’re thankful for.",
  "Engage in at least 20 minutes of physical activity to boost endorphins.",
  "Create a daily routine to help establish structure and consistency.",
  "Reach out to a friend, family member, or therapist for emotional support.",
  "Take small steps to get out of bed and accomplish one task, no matter how minor.",
  "Practice mindfulness meditation for 10-15 minutes to quiet your mind.",
  "Eat a balanced, nutritious meal to support both mental and physical well-being.",
  "Take regular breaks throughout the day to avoid overwhelming yourself.",
  "Get outside for fresh air and sunlight to support mood regulation.",
  "Focus on deep breathing exercises to calm your body and mind.",
  "Write in a journal to process your emotions and track your progress.",
  "Break large tasks into smaller, manageable steps to avoid feeling overwhelmed.",
  "Practice self-compassion and avoid harsh self-criticism.",
  "Celebrate small victories and progress, even if they seem insignificant.",
  "Spend time engaging in hobbies or activities you enjoy to lift your mood.",
  "Avoid isolating yourself—connect with others when possible.",
  "Engage in relaxation exercises like progressive muscle relaxation.",
  "Limit your time on social media to avoid negative comparisons.",
  "Ask for help with daily tasks or chores if you're feeling overwhelmed.",
  "Try using positive affirmations to challenge negative self-talk.",
  "Use a daily planner to organize and prioritize tasks.",
  "Create a calm and relaxing environment with soothing lighting and music.",
  "Set realistic goals and expectations for yourself to avoid unnecessary pressure.",
  "Avoid alcohol or substances that could worsen feelings of depression.",
  "Give yourself permission to rest when needed, without feeling guilty.",
  "Try cognitive behavioral techniques to challenge negative thoughts.",
  "Practice grounding techniques to stay present and manage overwhelming feelings.",
  "Take a break from work or stressful obligations to recharge.",
  "Join a support group or online community to connect with others going through similar experiences.",
  "Establish a sleep routine to ensure you're getting enough rest and recovery.",
  "Practice yoga or stretching exercises to relieve physical tension and improve mood.",
  "Try aromatherapy with calming scents like lavender or chamomile to improve emotional well-being.",
  "Consider reaching out to a therapist or counselor for professional support.",
  "Limit screen time, especially before bed, to improve sleep quality.",
  "Learn about and practice self-soothing techniques such as deep breathing or holding a comforting object.",
  "Stay hydrated and drink enough water throughout the day.",
  "Develop a daily mindfulness or meditation practice to cultivate awareness and presence.",
  "Create a ‘self-care toolkit’ with your favorite activities or items to engage with when feeling down.",
  "Spend time in nature, even if it's just a walk around the block.",
  "Avoid perfectionism and give yourself credit for simply getting through the day.",
  "Create a list of coping strategies you can refer to when feeling low.",
  "Practice self-care rituals like a warm bath, skincare routine, or reading your favorite book.",
  "Try to shift your focus from negative thoughts by engaging in a creative activity.",
  "Encourage yourself to take one small positive action at a time, without overwhelming yourself.",
  "Avoid making major decisions when feeling depressed—take your time.",
  "Practice kindness to yourself, recognizing that it's okay to have difficult days.",
  "Reframe negative thinking patterns using positive affirmations.",
  "Engage in a creative outlet like drawing, painting, or writing.",
  "Keep track of your mood patterns and look for triggers to better manage depression.",
  "Find one thing to look forward to each day, whether it’s a small treat or a relaxing moment.",
  "Try a gentle form of exercise, like swimming or walking, to lift your mood.",
  "Consider starting therapy or counseling, either in person or online.",
  "Practice mindfulness by focusing on your senses—what you can see, hear, smell, and feel.",
  "Identify negative thought patterns and replace them with more balanced perspectives.",
  "Practice compassion for others to reinforce positive feelings of connection and self-worth.",
  "Set aside time to rest and recharge without the pressure to be productive.",
  "Spend time with a pet for unconditional companionship and stress relief.",
  "Reflect on your values and how they can guide you through difficult times.",
  "Create a vision board or list of goals to visualize your aspirations and stay motivated.",
  "Engage in a daily gratitude practice by writing down things you appreciate about yourself and your life.",
  "Limit exposure to negative news or media that can exacerbate feelings of hopelessness.",
  "Practice self-acceptance and embrace your unique qualities and strengths.",
  "Reflect on your achievements and give yourself credit for your efforts.",
  "Engage in a power pose or confidence-boosting activity to improve your self-esteem.",
  "Create a list of positive affirmations or quotes that resonate with you.",
  "Reflect on how you can use this experience to grow and develop resilience for future challenges.",
  "Consider creating a crisis coping plan that includes your go-to strategies and support contacts for future reference.",
  "Practice gratitude by writing down three things you are thankful for, even in difficult times.",
  "Engage in a creative outlet (drawing, writing, etc.) to express your feelings and process the crisis.",
  "Limit exposure to negative influences or people who exacerbate your emotional state.",
  "Reflect on your emotional triggers and develop strategies to cope with them.",
  "Practice self-advocacy by expressing your needs and boundaries to others.",
  "Reflect on your values and how they can guide you through this crisis.",
];
