export const depressionSupportChecklist: string[] = [
  "Take a shower or bath",
  "Eat a nutritious meal",
  "Talk to a therapist or counselor",
  "Use mood tracking apps or journals for emotional awareness",
  "Develop a personalized 'early warning signs' checklist",
  "Create an uplifting playlist",
  "Do something nostalgic you loved as a kid",
  "Celebrate survival, not perfection",
  "Believe that tomorrow can be different",
  "Set a 5-minute tidy-up timer",
  "Listen to uplifting or calming music",
  "Create a small daily goal you can accomplish",
  "Eat a nourishing snack mindfully",
  "Spend 5 minutes sitting in the sun",
  "Try guided visualization meditation",
  "Incorporate value-driven activities aligned with personal meaning",
  "Focus on sensory grounding when emotional numbing occurs",
  "Apply self-forgiveness practices for perceived mistakes",
  "Prioritize sunlight exposure and circadian rhythm regulation",
  "Break down overwhelming tasks into micro-steps",
  "Challenge anhedonia by intentionally engaging curiosity",
  "Color in a mindfulness coloring page",
  "Plan one enjoyable thing for tomorrow",
  "Write yourself a compassionate letter",
  "Reach out to a friend or loved one",
  "Move your body gently (walk, stretch)",
  "Get fresh air outdoors",
  "Acknowledge your feelings without judgment",
  "Use opposite action: act contrary to depressive urges when safe",
  "Challenge hopelessness with evidence-based questioning",
  "Track daily accomplishments, no matter how small",
  "Write a list of things you're grateful for",
  "Create a small, achievable goal",
  "Watch a comforting show or movie",
  "Practice deep breathing",
  "Create an emotional emergency plan (contacts, coping strategies)",
  "Maintain a consistent sleep schedule",
  "Repeat a positive affirmation",
  "Declutter a small area of your home",
  "Reflect on a past success",
  "Schedule something enjoyable",
  "Text someone you trust, even a simple hello",
  "Make a 'comfort movie' list and pick one",
  "Behavioral activation: schedule and follow through on small, meaningful activities",
  "Use gratitude practices specifically for past moments of strength",
  "Write 'letters to self' for harder days",
  "Practice mindful savoring of small, positive moments",
  "Seek meaning even in minor, daily acts ('I mattered today because…')",
  "Give yourself permission to rest",
  "Use art or music for expression",
  "Spend time with a pet (if possible)",
  "Limit negative self-talk",
  "Remind yourself: 'I am doing my best.'",
  "Celebrate tiny victories",
  "Allow yourself to feel emotions fully",
  "Gently reconnect to pleasure through 'pleasure predicting' experiments",
  "Write down your wins for the day",
  "Spend 5 minutes sitting in sunlight",
  "Write a compassionate letter to yourself",
  "Set a timer for short bursts of productivity",
  "Listen to uplifting or soothing music",
  "Plan one small thing to look forward to",
  "Acknowledge your strength for enduring",
  "Create a simple daily routine",
  "Reframe self-critical thoughts with self-compassionate counter-statements",
  "Wear clothes that make you feel good",
  "Say one affirmation aloud",
  "Plan a self-kindness ritual",
  "Disconnect from technology for 1 hour",
  "Use a weighted blanket",
  "List one thing that gives you hope",
  "Practice stretching or slow yoga for 5 minutes",
  "List three neutral observations about today",
  "Visualize handing over the heavy burden you’re carrying temporarily",
  "Create a calm, cozy corner in your home",
  "Notice the sensations of breathing for 2 minutes",
  "Take a photo of something beautiful today",
  "Read a few pages of an inspiring book",
  "Remind yourself: 'This feeling is not forever.'",
  "Celebrate simply getting through the day",
];
