export const growthMindsetReflectionChecklist: string[] = [
  "Reflect on a recent challenge you faced. How did you approach it, and what did you learn from the experience?",
  "Identify a recent setback. What could you try differently next time, and how can you turn this experience into an opportunity for growth?",
  "Celebrate a recent success, big or small. How did your effort contribute to this success, and what strengths did you discover in yourself?",
  "Think of an area where you want to improve. What steps can you take to grow in that area, and how will you measure your progress?",
  "Consider a skill you’ve developed over time. What strategies helped you improve, and how can you apply these strategies to other areas?",
  "Recognize a negative thought you’ve had about your abilities. Reframe it with a more positive or constructive perspective.",
  "Reflect on a time when you faced criticism. How did you handle it, and how can you use feedback to enhance your growth?",
  "Think about someone you admire for their perseverance and growth. What qualities do they have that you can adopt to further your own growth mindset?",
  "Consider a task or goal you’ve been avoiding. What’s one small step you can take to start moving forward with it?",
  "Reflect on a situation where you felt frustrated or discouraged. What is one action you can take to turn that frustration into a learning opportunity?",
  "Identify a belief you hold about your abilities. How can you challenge this belief and see it as a skill that can be developed?",
  "Consider an area of personal growth that excites you. What resources or tools do you need to start making progress?",
  "Think about a time when you felt out of your comfort zone. What did that experience teach you about your own resilience?",
  "Reflect on a recent failure. What was the lesson, and how can you apply it to future challenges?",
  "Think about a personal habit you’d like to improve. What mindset shift would help you make lasting changes?",
  "Consider how you view effort in relation to success. Do you see effort as a path to improvement, or do you feel discouraged by the amount of effort required?",
  "Reflect on a situation where you learned something new. What steps did you take to grasp this new concept, and how can you apply the same approach to other areas?",
  "Identify a belief about your limitations. How can you work on changing that belief to focus on your potential for growth?",
  "Think about a recent learning experience. How can you break it down into smaller, more manageable pieces for future growth?",
  "Consider a habit you’ve recently developed. How has consistency played a role in your growth, and how can you apply this consistency to other areas of your life?",
  "Reflect on how you approach failure. Do you view it as a final outcome or as part of the learning process?",
  "Think about someone who has shown tremendous growth in their life. What mindset or strategies have they used that you can apply to your own journey?",
  "Identify an area where you feel stuck. What questions can you ask yourself to shift your perspective and unlock new approaches?",
  "Consider how you’ve handled stress or setbacks in the past. How can you use these experiences to develop new, more effective coping strategies?",
  "Reflect on your current level of resilience. What has helped you build this resilience, and how can you continue strengthening it?",
  "Think about a recent challenge you overcame. What tools or strategies helped you succeed, and how can you apply them again?",
  "Consider a growth opportunity you’ve been hesitant to pursue. What’s one small action you can take today to move forward?",
  "Reflect on how you respond to mistakes. How can you use mistakes as stepping stones to personal growth?",
  "Identify one area of your life where you want to improve. What’s the first small step you can take to make progress?",
  "Think about your past experiences. How can you use them as evidence that growth is possible, even in the face of difficulty?",
  "Consider the phrase 'failure is feedback.' What recent experience can you apply this mindset to, and how will it shift your perspective?",
  "Reflect on how far you’ve come in your personal growth journey. What strengths can you identify in yourself that will help you continue progressing?",
  "Think about a challenge you're currently facing. What resources or support could help you overcome this obstacle?",
  "Consider your emotional responses to setbacks. How can you reframe your emotions to stay positive and focused on growth?",
  "Identify a positive affirmation you can use to reinforce a growth mindset in your daily life.",
  "Reflect on how you can celebrate even the smallest victories to maintain motivation in your growth journey.",
  "Think about how you approach new learning opportunities. Are you open to challenges, or do you shy away from them? How can you embrace challenges with a growth mindset?",
  "Consider how you handle success. Do you attribute it solely to talent, or do you recognize the effort and persistence that contributed to your achievement?",
  "Reflect on the importance of persistence. How have you seen persistence lead to success in your own life or others’?",
  "Identify a personal value or principle that supports your growth mindset. How can you cultivate and reinforce this value in your life?",
  "Think about an area where you’re still growing. What specific goals can you set to continue improving in that area?",
  "Consider the role of patience in growth. How can you practice patience with yourself as you continue to develop new skills?",
  "Reflect on how you view challenges. Do you see them as threats, or do you see them as opportunities to expand your abilities?",
  "Think about how you celebrate progress. How can you create a habit of acknowledging your growth, no matter how small the achievement?",
  "Consider the mindset shift that can turn obstacles into opportunities. How can you apply this shift to your current challenges?",
];
