export const healthySleepHygieneChecklist: string[] = [
  "Set a consistent sleep schedule by going to bed and waking up at the same time every day, even on weekends.",
  "Create a calming bedtime routine, such as reading, taking a warm bath, or practicing relaxation techniques before bed.",
  "Avoid caffeine and heavy meals at least 4-6 hours before bedtime.",
  "Limit alcohol consumption, as it can interfere with deep sleep and cause frequent awakenings.",
  "Reduce screen time (phones, computers, TV) at least 30 minutes to an hour before bed to help your body wind down.",
  "Ensure your sleep environment is comfortable—consider the temperature, bedding, and overall cleanliness of your room.",
  "Keep your bedroom dark and quiet, using blackout curtains or an eye mask and eliminating any distracting noises.",
  "Engage in physical activity during the day, but avoid vigorous exercise close to bedtime.",
  "Limit naps during the day, especially in the late afternoon or evening, to avoid disrupting your nighttime sleep.",
  "Create a sleep-friendly atmosphere by minimizing light exposure, especially blue light from digital devices.",
  "Avoid looking at the clock during the night to prevent anxiety about sleep duration or waking up.",
  "Practice mindfulness, meditation, or deep breathing exercises to calm your mind before sleep.",
  "Keep your bedroom exclusively for sleep and relaxation; avoid working or using electronic devices in bed.",
  "Use a comfortable mattress and pillows that support good sleep posture and comfort.",
  "Be mindful of your intake of liquids before bed to avoid waking up for bathroom trips during the night.",
  "If you can’t fall asleep within 20 minutes, get out of bed and do something relaxing, like reading or listening to calming music.",
  "Expose yourself to natural sunlight during the day, particularly in the morning, to help regulate your internal sleep-wake cycle.",
  "Avoid heavy or intense mental stimulation right before bedtime—engage in calming activities instead.",
  "Ensure your bedroom is at a cool, comfortable temperature for sleep—typically between 60-67°F (15-19°C).",
  "Try a sleep journal to track your sleep patterns and any potential factors that could be disrupting your rest.",
  "Avoid using your bed for anything other than sleeping and intimate activities to reinforce the connection between bed and sleep.",
  "Establish a set routine for going to sleep, such as dimming lights and engaging in quiet activities to signal to your body that it's time to wind down.",
  "Use aromatherapy, such as lavender essential oil, to create a calming environment conducive to sleep.",
  "Create a sleep sanctuary by eliminating distractions, including noise, clutter, and any unnecessary distractions in your bedroom.",
  "Establish a pre-sleep routine that signals your body it’s time to wind down—this could include drinking herbal tea, stretching, or reading.",
  "Avoid stressful conversations or activities right before bed, as these can interfere with the relaxation needed to fall asleep.",
  "Stay mindful of your sleep cycle—try to get at least 7-9 hours of sleep every night for optimal health.",
  "Consider using white noise or a sound machine if you're sensitive to environmental noises that may disturb your sleep.",
  "Avoid stimulating substances like nicotine before bed, as it can disrupt sleep and keep you awake.",
  "Create a sleep-friendly evening environment by dimming the lights and making your surroundings cozy and inviting.",
  "Use cognitive behavioral techniques, such as thought-stopping or visualization, if you struggle with racing thoughts before bed.",
  "Try progressive muscle relaxation before bed to reduce stress and prepare your body for rest.",
  "Practice good posture throughout the day to avoid tension that could negatively affect your sleep at night.",
  "Limit exposure to loud sounds or stressful situations in the hours leading up to bedtime to help you unwind.",
  "Ensure your bedroom is well-ventilated to keep the air fresh, which can aid in falling asleep faster and staying asleep throughout the night.",
  "Avoid consuming large amounts of liquids after 8 p.m. to minimize the chances of waking up to go to the bathroom.",
  "Turn off bright lights and use dim lamps if you need to get up during the night, as bright light exposure can disrupt your sleep cycle.",
  "Consider sleep tracking apps or devices to monitor your sleep habits and make improvements to your sleep hygiene routine.",
  "Be patient with yourself as you establish healthy sleep habits—it may take time to adjust, but consistency is key to success.",
  "Create a relaxing evening routine that calms your mind and signals to your body that it's time to unwind for the night.",
  "Make sure to allow enough time for quality sleep each night, as insufficient rest can have long-term effects on your health and well-being.",
  "If you experience persistent sleep problems, consider speaking with a healthcare professional or sleep specialist for guidance.",
];
