export const innerStrengthBuilderChecklist: string[] = [
  "Identify three personal values that guide your decisions.",
  "List five strengths you’ve used to overcome challenges.",
  "Reflect on a time you persevered through adversity and what it taught you.",
  "Write down three affirmations that reinforce your self-worth.",
  "Recall a compliment that deeply resonated with you and why it mattered.",
  "Describe a decision you made that made you feel proud and empowered.",
  "Name a role model who inspires your resilience and describe why.",
  "Write a letter to your past self acknowledging your growth and strength.",
  "List things in your life that bring you meaning, purpose, or peace.",
  "Visualize yourself overcoming your current challenges with strength and grace.",
  "Note a habit you’ve built that has made you mentally or emotionally stronger.",
  "Practice gratitude by writing down five things you’re thankful for today.",
  "Identify a fear you’ve conquered and what helped you overcome it.",
  "Recall a time you set a boundary and how it strengthened your self-respect.",
  "Name an activity or hobby that helps you reconnect with yourself.",
  "Reflect on a setback you turned into a learning experience.",
  "List three people you can count on for support when times get hard.",
  "Think of a time you advocated for yourself—what gave you the courage?",
  "Create a mantra that reminds you of your inner strength during tough moments.",
  "Identify a belief about yourself that you’ve changed for the better.",
  "Write down one thing you’ve done recently that scared you—but you did it anyway.",
  "Set a micro-goal for the week and celebrate when you complete it.",
  "Describe how you’ve helped someone else and how that made you feel stronger.",
  "Recall a mistake you made and how you grew from it.",
  "List five qualities you admire in yourself.",
  "Challenge a self-limiting belief and write a more empowering version.",
  "Think of a time you were rejected or failed and what you learned.",
  "Describe what resilience means to you in your own words.",
  "Track your emotional ups and downs for a week and reflect on patterns.",
  "Practice saying no to something that doesn’t serve your growth.",
  "Write a future journal entry imagining you’ve achieved your goals.",
  "List three ways you’ve grown in the past year.",
  "Recognize an unhealthy coping mechanism you’ve replaced with a better one.",
  "Make a list of boundaries you need to reinforce for your well-being.",
  "Identify a trigger and describe how you manage your response to it.",
  "Write about what gives your life a sense of purpose.",
  "Celebrate a recent win—big or small—and how it reflects your growth.",
  "Name one way you show up for yourself daily.",
  "Write about a difficult conversation you’ve had and how it made you stronger.",
  "Identify one self-care ritual that makes you feel grounded and strong.",
  "Reflect on how you’ve changed your perspective on a past challenge.",
  "List three things you can do to nurture your inner strength this week.",
  "Think of a time you felt truly at peace. What contributed to that feeling?",
  "Write about a time you felt empowered to make a change in your life.",
  "Identify a skill you want to develop and outline steps to achieve it.",
  "Reflect on how you can use your strengths to help others in your community.",
  "List three things you can do to practice self-compassion.",
];
