export const resilientThinkingHabitsChecklist: string[] = [
  "Focus on solutions rather than problems when facing challenges.",
  "Accept that setbacks are a natural part of the journey, not the end of it.",
  "Practice mindfulness to stay present and avoid overthinking the past or future.",
  "Challenge negative thoughts by questioning their validity and replacing them with more realistic alternatives.",
  "Celebrate small wins, acknowledging progress even on difficult days.",
  "Adopt a growth mindset, believing that challenges help you learn and grow.",
  "Build a support network of positive, resilient individuals who uplift you during tough times.",
  "Maintain flexibility in your approach, knowing that plans may need to change to adapt to new circumstances.",
  "Embrace mistakes as learning opportunities, focusing on what you can improve moving forward.",
  "Develop a strong sense of purpose that guides you during moments of uncertainty or adversity.",
  "Foster patience with yourself, recognizing that growth takes time and persistence.",
  "Practice gratitude daily to keep your focus on the positive aspects of your life.",
  "Visualize overcoming obstacles and achieving success, building confidence in your ability to persevere.",
  "Take responsibility for your thoughts and actions, empowering yourself to change your mindset.",
  "Set clear, realistic goals that align with your values and give you a sense of direction.",
  "Identify your strengths and use them as tools to navigate challenges effectively.",
  "Regularly assess and adjust your mental health practices to ensure you're taking care of your emotional well-being.",
  "Engage in activities that help reduce stress, such as exercise, meditation, or creative hobbies.",
  "Limit negative influences, such as toxic environments or individuals that drain your energy.",
  "Focus on what you can control, letting go of things outside your influence to prevent unnecessary stress.",
  "Practice self-compassion by speaking to yourself kindly and forgiving yourself for past mistakes.",
  "Learn from the resilience of others by reading stories, biographies, or talking to people who inspire you.",
  "Seek professional help when necessary, understanding that asking for support is a sign of strength, not weakness.",
  "Track your emotional responses to different situations to identify patterns and triggers that you can address.",
  "Set aside time for self-reflection, regularly checking in with your thoughts, feelings, and goals.",
  "Be proactive in building mental resilience by practicing coping strategies before you need them.",
  "Take time to recharge when you feel mentally or physically exhausted, recognizing that self-care is essential to long-term resilience.",
  "Accept that not everything is within your control and learn to let go of perfectionism.",
  "Remind yourself that difficult times don’t last, but your resilience will.",
  "Foster optimism by focusing on the potential benefits and opportunities in every challenge.",
  "Avoid catastrophizing by focusing on the facts rather than imagining worst-case scenarios.",
  "Stay connected to your sense of purpose, even in the face of adversity, by remembering why you started.",
  "Practice mental flexibility, adjusting your thoughts and actions to better align with your current reality.",
  "Recognize your emotional triggers and take steps to manage them before they escalate.",
  "Reframe negative experiences as opportunities for personal growth, seeing every challenge as a chance to become stronger.",
  "Encourage yourself to take risks, knowing that stepping outside your comfort zone builds resilience.",
  "Accept that resilience is a skill that requires ongoing practice and commitment.",
  "Prioritize rest and recovery, as physical well-being is closely tied to mental resilience.",
  "Establish a routine that includes activities that promote mental, emotional, and physical health.",
  "Use affirmations to remind yourself of your strength, resilience, and ability to handle challenges.",
  "Stay curious and open-minded, seeing each challenge as a chance to explore new solutions.",
  "Set boundaries to protect your energy and prevent burnout.",
  "Be kind to others and offer support when you can, as helping others can also strengthen your own resilience.",
  "Practice problem-solving by breaking down challenges into manageable steps rather than feeling overwhelmed by the whole task.",
  "Track your progress in building resilience, recognizing how far you’ve come and celebrating your growth.",
  "Reflect on your past experiences of resilience, reminding yourself of how you overcame previous obstacles.",
  "Embrace uncertainty, knowing that resilience is about adapting to the unknown and staying calm in the face of it.",
  "Recognize when you're feeling overwhelmed and practice grounding techniques to stay centered.",
  "Take ownership of your mental health journey, creating a personalized plan for building resilience over time.",
  "Celebrate your resilience, acknowledging that every challenge you've faced has made you stronger.",
  "Engage in daily acts of kindness to yourself and others, as small acts of positivity help to build mental resilience.",
  "Maintain a positive inner dialogue, replacing self-doubt with affirmations of strength and capability.",
  "Focus on building emotional intelligence, which helps you understand and manage your emotions effectively in times of stress.",
  "Incorporate deep breathing exercises into your daily routine to help reduce stress and improve focus.",
  "Revisit and redefine your goals as necessary, ensuring they align with your changing values and circumstances.",
  "Embrace the process of healing and growth, knowing that setbacks do not define you but strengthen you in the long run.",
  "Practice active listening in conversations, as it fosters connection and understanding with others.",
  "Engage in community activities or volunteer work to foster a sense of belonging and purpose.",
];
