export const socialConnectionChecklist: string[] = [
  "Reach out to at least one friend or family member every week.",
  "Engage in meaningful conversations that go beyond surface-level topics.",
  "Make time for social activities, even if it's just a virtual hangout.",
  "Show genuine interest in others' lives and well-being.",
  "Join a community or group that aligns with your interests or values.",
  "Practice active listening during conversations, focusing on understanding rather than responding.",
  "Offer support to others when they need it, whether emotionally or practically.",
  "Initiate plans with others, taking the first step to build or maintain connections.",
  "Express gratitude towards the people you care about to strengthen bonds.",
  "Be open to meeting new people and forming new friendships.",
  "Cultivate empathy by trying to understand other people's perspectives and feelings.",
  "Share positive experiences with friends and family to create shared memories.",
  "Reach out to old friends or acquaintances you haven't spoken to in a while.",
  "Stay in touch with colleagues and peers to foster professional relationships.",
  "Be vulnerable and authentic in your relationships, allowing for deeper connections.",
  "Support others in their goals and aspirations, celebrating their successes.",
  "Offer encouragement and understanding during difficult times.",
  "Participate in social events that contribute to your mental well-being.",
  "Avoid isolation by keeping regular communication with those around you.",
  "Take part in collaborative activities, whether in-person or online, to bond with others.",
  "Set aside distractions when spending time with others to focus on the moment.",
  "Join an online group or forum to connect with like-minded individuals.",
  "Host gatherings, whether virtual or in-person, to create a sense of community.",
  "Make time for casual social interactions, such as a coffee break with a colleague or a short chat with a neighbor.",
  "Check in on your friends and family members to show that you care.",
  "Make a habit of giving compliments or positive feedback to the people around you.",
  "Respect boundaries and be considerate of others' needs when forming or maintaining connections.",
  "Volunteer for causes or organizations that matter to you, fostering a sense of belonging.",
  "Be present and engaged when interacting with others, avoiding distractions like phones.",
  "Make an effort to maintain long-distance relationships through video calls, messages, or letters.",
  "Create opportunities for shared experiences, like cooking together, attending events, or enjoying a hobby.",
  "Encourage others to express their feelings and be supportive when they do.",
  "Promote open and honest communication to avoid misunderstandings and build trust.",
  "Practice gratitude in your relationships by acknowledging the people who positively impact your life.",
  "Set time aside regularly to engage in social activities that bring you joy.",
  "Be kind and patient with others, knowing that not everyone has the same needs or experiences.",
  "Create a balance between socializing and personal time to ensure you feel emotionally supported.",
  "Engage in group activities like sports, exercise classes, or book clubs to meet new people.",
  "Use social media mindfully by following accounts that inspire positive connections and avoid negativity.",
  "Make a point to check in with people who may be struggling emotionally or mentally.",
  "Be open to seeking help from friends, family, or professionals when you need it.",
  "Engage in shared hobbies with others to deepen your connections through common interests.",
  "Allow yourself to say no when needed, recognizing that social energy must be managed.",
  "Respect diversity and inclusivity, valuing different perspectives and backgrounds in your relationships.",
  "Be patient with yourself in building or maintaining social connections, especially if you’ve experienced isolation.",
  "Find balance in your social life, avoiding overcommitment while still staying connected.",
  "Foster kindness and respect in all your interactions, whether with strangers or close friends.",
  "Invite others to share their stories and experiences, which can foster deeper connections.",
  "Encourage a positive social environment where everyone feels comfortable and valued.",
  "Practice forgiveness in your relationships to resolve conflicts and strengthen trust.",
  "Make regular effort to strengthen your emotional support system by nurturing meaningful connections.",
  "Create safe spaces for others to express themselves, offering compassion without judgment.",
  "Stay open to growth in your relationships, willing to adapt and change as needed.",
  "Reflect on your social connections regularly, assessing which relationships uplift you and which may need reevaluation.",
  "Engage in activities that promote teamwork and collaboration, enhancing your social skills.",
  "Practice self-care to ensure you are emotionally available for others.",
  "Be mindful of your body language and non-verbal cues when interacting with others.",
];
