export const supportNetworkEngagementChecklist: string[] = [
  "Identify and reach out to key people in your support network (friends, family, mentors, or colleagues).",
  "Schedule regular check-ins with close friends or family to maintain emotional connection.",
  "Join a community group or club that aligns with your interests or values to build new support connections.",
  "Attend social gatherings, events, or online meetups to expand your circle and engage with like-minded people.",
  "Offer support to others in your network, as helping others strengthens your relationships.",
  "Make time for face-to-face interactions, whether in-person or via video calls, to strengthen bonds.",
  "Express appreciation to the people in your support network for their love, guidance, and assistance.",
  "Be open and honest with your support network about your needs and feelings to create stronger connections.",
  "Seek professional support from a therapist, counselor, or coach when necessary to ensure emotional well-being.",
  "Engage in group activities or team projects that foster collaboration and shared experiences.",
  "Offer to be a resource or support for someone in your network who may be going through a difficult time.",
  "Set boundaries to protect your time and energy while still maintaining meaningful relationships.",
  "Reach out to old friends or acquaintances to reconnect and rekindle important relationships.",
  "Engage in mutual support by helping others achieve their personal goals and celebrating their successes.",
  "Check in with loved ones regularly to see how they are doing and offer support when needed.",
  "Be consistent in your communication and show that you genuinely care about the well-being of others.",
  "Attend therapy or support groups to find additional emotional support and share experiences with others.",
  "Engage in active listening during conversations, showing empathy and understanding for others’ feelings.",
  "Participate in group activities, workshops, or seminars to broaden your social network and meet new people.",
  "Stay connected with a mentor or advisor who can provide guidance and wisdom for personal growth.",
  "Invite people in your support network to share experiences and insights with one another, creating a strong community.",
  "Organize or participate in social events or gatherings to maintain healthy, supportive relationships.",
  "Be a consistent and reliable presence in the lives of those who rely on you for support.",
  "Create opportunities for mutual care, such as shared meals, walks, or activities with loved ones.",
  "Reach out to others when you're in need, and remember that asking for help is a sign of strength, not weakness.",
  "Share your successes and challenges with your network to encourage open, two-way communication.",
  "Seek out online support groups, forums, or communities if you need additional emotional or practical support.",
  "Learn from the people in your support network by asking for advice or guidance during challenging times.",
  "Make an effort to maintain relationships with people who uplift and support your personal values and goals.",
  "Show appreciation through small gestures, like sending thank-you notes or offering help in return.",
  "Be patient with yourself and others, recognizing that everyone has unique challenges and timelines for growth.",
  "Stay connected with people who encourage you to grow and improve, both personally and professionally.",
  "Support your network through both emotional and practical means, such as offering assistance with tasks or chores.",
  "Join peer-support groups that focus on personal development, mental health, or shared experiences.",
  "Cultivate gratitude within your support network, expressing thankfulness for the people who help you along your journey.",
  "Prioritize quality over quantity when it comes to your support network; a few trusted relationships can be more beneficial than many casual ones.",
  "Encourage others to share their challenges, creating an open space for vulnerability and healing.",
  "Stay connected through regular texts, phone calls, or virtual check-ins, especially during difficult times.",
  "Set intentions for your interactions with your support network, aiming for meaningful and uplifting conversations.",
  "Respect the boundaries of others while still providing care, empathy, and attention to their needs.",
  "Strengthen your relationship with family members by creating time for bonding activities or open dialogue.",
  "Find ways to help others feel valued and appreciated by acknowledging their contributions to your life.",
  "Create a list of trusted individuals who can offer advice or assistance in times of need and make sure to engage with them regularly.",
  "Be proactive about checking in on those who may need extra support during difficult times or life transitions.",
  "Maintain a balance between personal and professional support, ensuring that your network supports all areas of your life.",
  "Practice patience when developing new relationships, recognizing that trust and connection take time to build.",
];
